/* ==================================================================
   영어 단어 사전 — 난이도별 400개씩 1200개

   한 줄에 [단어, 뜻, 예문, 예문 번역] 네 가지를 담는다. 예문의 ___
   자리에 그 단어가 들어간다 (빈칸 채우기 문제에 쓴다). 예문 번역은
   단어 도감에서 "이 단어가 실제로 어떻게 쓰이는지"를 한국어로도
   보여주기 위한 것이다 — 영어만 봐서는 문장 전체 뜻까지는 알기
   어렵다.

   객체 대신 배열로 적은 이유: 1200줄이 되면 { word: ..., meaning: ... }
   형식은 읽을 때 눈이 피로하고, 만들어 낸 HTML 파일도 그만큼 커진다.
   줄마다 순서가 같으니 헷갈릴 일도 없다.

   난이도 규칙 (테스트가 이 규칙을 그대로 검사한다)
     easy    7글자 이하
     normal  12글자 이하
     hard    10글자 이상
   ================================================================== */

export const WORD_FIELDS = ['word', 'meaning', 'sentence', 'translation']

/* ------------------------------------------------------------------
   초급 — 7글자 이하. 일상에서 매일 마주치는 말들.
   ------------------------------------------------------------------ */
const easy = [
  ['apple', '사과', 'She ate a red ___ after lunch.', '그녀는 점심을 먹고 빨간 사과를 먹었다.'],
  ['book', '책', 'I borrowed a ___ from the library.', '나는 도서관에서 책을 한 권 빌렸다.'],
  ['water', '물', 'Please drink more ___ every day.', '매일 물을 더 많이 마시세요.'],
  ['happy', '행복한', 'The children look very ___ today.', '아이들이 오늘 매우 행복해 보인다.'],
  ['house', '집', 'They bought a small ___ near the park.', '그들은 공원 근처의 작은 집을 샀다.'],
  ['school', '학교', 'My sister walks to ___ every morning.', '내 여동생은 매일 아침 학교까지 걸어간다.'],
  ['friend', '친구', 'He is my closest ___ from childhood.', '그는 어릴 적부터 나의 가장 친한 친구이다.'],
  ['family', '가족', 'Our whole ___ gathers every winter.', '우리 가족은 겨울마다 다 함께 모인다.'],
  ['market', '시장', 'We buy fresh fish at the ___ .', '우리는 시장에서 신선한 생선을 산다.'],
  ['garden', '정원', 'Roses bloom in her small ___ .', '그녀의 작은 정원에 장미가 핀다.'],
  ['animal', '동물', 'The lion is a wild ___ .', '사자는 야생 동물이다.'],
  ['flower', '꽃', 'He gave her a yellow ___ .', '그는 그녀에게 노란 꽃을 주었다.'],
  ['summer', '여름', 'We swim in the sea every ___ .', '우리는 여름마다 바다에서 수영한다.'],
  ['winter', '겨울', 'It snows a lot in ___ .', '겨울에는 눈이 많이 온다.'],
  ['spring', '봄', 'Trees turn green in ___ .', '봄이 되면 나무들이 초록빛으로 변한다.'],
  ['morning', '아침', 'I drink tea every ___ .', '나는 매일 아침 차를 마신다.'],
  ['night', '밤', 'The stars shine at ___ .', '밤에는 별이 빛난다.'],
  ['kitchen', '부엌', 'Mother is cooking in the ___ .', '어머니는 부엌에서 요리하고 계신다.'],
  ['bedroom', '침실', 'My ___ has a large window.', '내 침실에는 큰 창문이 있다.'],
  ['window', '창문', 'Please open the ___ for fresh air.', '환기를 위해 창문을 열어 주세요.'],
  ['table', '탁자', 'Put the plates on the ___ .', '접시들을 탁자 위에 놓아라.'],
  ['chair', '의자', 'He sat on a wooden ___ .', '그는 나무 의자에 앉았다.'],
  ['phone', '전화기', 'My ___ battery died this morning.', '오늘 아침 내 전화기 배터리가 다 됐다.'],
  ['letter', '편지', 'She wrote a long ___ to her father.', '그녀는 아버지께 긴 편지를 썼다.'],
  ['music', '음악', 'I listen to ___ while studying.', '나는 공부할 때 음악을 듣는다.'],
  ['dance', '춤추다', 'They love to ___ at weddings.', '그들은 결혼식에서 춤추는 것을 좋아한다.'],
  ['color', '색깔', 'Blue is my favorite ___ .', '파란색은 내가 가장 좋아하는 색깔이다.'],
  ['bread', '빵', 'He baked fresh ___ this morning.', '그는 오늘 아침 신선한 빵을 구웠다.'],
  ['cheese', '치즈', 'This pizza has too much ___ .', '이 피자에는 치즈가 너무 많다.'],
  ['coffee', '커피', 'She drinks black ___ without sugar.', '그녀는 설탕 없이 블랙커피를 마신다.'],
  ['sugar', '설탕', 'Add two spoons of ___ .', '설탕 두 스푼을 넣어라.'],
  ['salt', '소금', 'The soup needs more ___ .', '이 수프는 소금이 좀 더 필요하다.'],
  ['pepper', '후추', 'Sprinkle some ___ on the eggs.', '계란 위에 후추를 조금 뿌려라.'],
  ['dinner', '저녁 식사', 'We eat ___ together at seven.', '우리는 일곱 시에 함께 저녁을 먹는다.'],
  ['lunch', '점심', 'I had a quick ___ at my desk.', '나는 책상에서 간단히 점심을 먹었다.'],
  ['plate', '접시', 'He dropped the glass ___ .', '그는 유리 접시를 떨어뜨렸다.'],
  ['spoon', '숟가락', 'Stir the soup with a ___ .', '숟가락으로 수프를 저어라.'],
  ['knife', '칼', 'Cut the bread with a sharp ___ .', '날카로운 칼로 빵을 잘라라.'],
  ['glass', '유리잔', 'Pour the juice into a ___ .', '주스를 유리잔에 부어라.'],
  ['bottle', '병', 'She carried a ___ of water.', '그녀는 물 한 병을 들고 있었다.'],
  ['basket', '바구니', 'The ___ is full of apples.', '바구니는 사과로 가득하다.'],
  ['money', '돈', 'He saved ___ for a new bike.', '그는 새 자전거를 사려고 돈을 모았다.'],
  ['price', '가격', 'The ___ of rice went up.', '쌀 가격이 올랐다.'],
  ['store', '가게', 'That ___ opens at nine.', '그 가게는 아홉 시에 문을 연다.'],
  ['street', '거리', 'Cars filled the narrow ___ .', '좁은 거리에 차들이 가득했다.'],
  ['city', '도시', 'Seoul is a busy ___ .', '서울은 분주한 도시이다.'],
  ['town', '마을', 'She grew up in a quiet ___ .', '그녀는 조용한 마을에서 자랐다.'],
  ['river', '강', 'A long ___ runs through the valley.', '긴 강이 계곡을 따라 흐른다.'],
  ['ocean', '바다', 'The ___ looks calm today.', '오늘은 바다가 잔잔해 보인다.'],
  ['beach', '해변', 'We walked along the sandy ___ .', '우리는 모래 해변을 따라 걸었다.'],
  ['forest', '숲', 'Many birds live in this ___ .', '이 숲에는 많은 새들이 산다.'],
  ['hill', '언덕', 'They climbed the green ___ .', '그들은 초록빛 언덕을 올랐다.'],
  ['field', '들판', 'Cows graze in the open ___ .', '소들이 넓은 들판에서 풀을 뜯는다.'],
  ['island', '섬', 'We took a boat to the ___ .', '우리는 배를 타고 섬으로 갔다.'],
  ['bridge', '다리', 'The old ___ crosses the river.', '오래된 다리가 강을 가로지른다.'],
  ['train', '기차', 'The ___ leaves at six sharp.', '기차는 정각 여섯 시에 출발한다.'],
  ['plane', '비행기', 'Our ___ landed on time.', '우리 비행기는 제시간에 착륙했다.'],
  ['ship', '배', 'The ___ sailed at dawn.', '배는 새벽에 출항했다.'],
  ['travel', '여행하다', 'They ___ abroad every summer.', '그들은 매년 여름 해외로 여행한다.'],
  ['ticket', '표', 'I lost my concert ___ .', '나는 콘서트 표를 잃어버렸다.'],
  ['hotel', '호텔', 'We stayed at a small ___ .', '우리는 작은 호텔에 묵었다.'],
  ['sleep', '자다', 'Babies ___ most of the day.', '아기들은 하루의 대부분을 잔다.'],
  ['dream', '꿈', 'She had a strange ___ last night.', '그녀는 어젯밤 이상한 꿈을 꾸었다.'],
  ['walk', '걷다', 'Let us ___ to the station.', '역까지 걸어가자.'],
  ['jump', '뛰다', 'The cat can ___ very high.', '그 고양이는 매우 높이 뛸 수 있다.'],
  ['swim', '수영하다', 'He learned to ___ at age five.', '그는 다섯 살에 수영을 배웠다.'],
  ['climb', '오르다', 'They plan to ___ that mountain.', '그들은 저 산을 오를 계획이다.'],
  ['throw', '던지다', 'Do not ___ stones at birds.', '새들에게 돌을 던지지 마라.'],
  ['catch', '잡다', 'Try to ___ the ball with both hands.', '두 손으로 공을 잡아 보아라.'],
  ['carry', '나르다', 'Can you ___ this heavy box?', '이 무거운 상자를 나를 수 있니?'],
  ['push', '밀다', 'Please ___ the door gently.', '문을 살살 밀어 주세요.'],
  ['pull', '당기다', 'You must ___ the handle hard.', '손잡이를 세게 당겨야 한다.'],
  ['open', '열다', 'Could you ___ the window?', '창문을 열어 줄 수 있니?'],
  ['close', '닫다', 'Remember to ___ the gate.', '문을 닫는 것을 잊지 마라.'],
  ['break', '부수다', 'Be careful not to ___ the vase.', '꽃병을 깨지 않도록 조심해라.'],
  ['build', '짓다', 'They will ___ a new library.', '그들은 새 도서관을 지을 것이다.'],
  ['clean', '청소하다', 'I ___ my room every Saturday.', '나는 매주 토요일마다 방을 청소한다.'],
  ['wash', '씻다', 'Please ___ your hands first.', '먼저 손을 씻으세요.'],
  ['cook', '요리하다', 'He likes to ___ Italian food.', '그는 이탈리아 음식을 요리하는 것을 좋아한다.'],
  ['drink', '마시다', 'Do not ___ cold water too fast.', '찬물을 너무 빨리 마시지 마라.'],
  ['taste', '맛보다', 'Would you like to ___ this soup?', '이 수프를 맛보시겠어요?'],
  ['smell', '냄새 맡다', 'I can ___ fresh bread.', '갓 구운 빵 냄새가 난다.'],
  ['touch', '만지다', 'Do not ___ the wet paint.', '젖은 페인트를 만지지 마라.'],
  ['listen', '귀 기울이다', 'Please ___ to the teacher.', '선생님 말씀에 귀 기울이세요.'],
  ['speak', '말하다', 'She can ___ three languages.', '그녀는 세 가지 언어를 말할 수 있다.'],
  ['answer', '대답하다', 'He did not ___ my question.', '그는 내 질문에 대답하지 않았다.'],
  ['write', '쓰다', 'Please ___ your name here.', '여기에 이름을 써 주세요.'],
  ['draw', '그리다', 'He can ___ birds very well.', '그는 새를 아주 잘 그린다.'],
  ['learn', '배우다', 'Children ___ quickly at that age.', '아이들은 그 나이에 빠르게 배운다.'],
  ['teach', '가르치다', 'She will ___ math next year.', '그녀는 내년에 수학을 가르칠 것이다.'],
  ['study', '공부하다', 'They ___ together every evening.', '그들은 매일 저녁 함께 공부한다.'],
  ['think', '생각하다', 'Let me ___ about it tonight.', '오늘 밤 그것에 대해 생각해 볼게.'],
  ['forget', '잊다', 'Do not ___ your umbrella.', '우산을 잊지 마라.'],
  ['hope', '바라다', 'We ___ the weather stays clear.', '우리는 날씨가 계속 맑기를 바란다.'],
  ['want', '원하다', 'What do you ___ for dinner?', '저녁으로 무엇을 원하니?'],
  ['love', '사랑하다', 'They ___ their grandchildren dearly.', '그들은 손주들을 몹시 사랑한다.'],
  ['laugh', '웃다', 'His jokes always make us ___ .', '그의 농담은 항상 우리를 웃게 한다.'],
  ['smile', '미소짓다', 'She began to ___ warmly.', '그녀는 따뜻하게 미소 짓기 시작했다.'],
  ['shout', '소리치다', 'Do not ___ in the library.', '도서관에서 소리치지 마라.'],
  ['help', '돕다', 'Can you ___ me carry this?', '이거 나르는 것 좀 도와줄 수 있니?'],
  ['share', '나누다', 'Please ___ the candy with your sister.', '여동생과 사탕을 나눠 먹어라.'],
  ['bring', '가져오다', 'Do not forget to ___ your notebook.', '공책 가져오는 것을 잊지 마라.'],
  ['send', '보내다', 'I will ___ the file tonight.', '오늘 밤에 파일을 보낼게.'],
  ['sell', '팔다', 'They ___ vegetables at the corner.', '그들은 길모퉁이에서 채소를 판다.'],
  ['count', '세다', 'Please ___ the chairs again.', '의자를 다시 세어 보세요.'],
  ['number', '숫자', 'Write your phone ___ here.', '여기에 전화번호를 적으세요.'],
  ['week', '주', 'I will visit you next ___ .', '다음 주에 너를 방문할게.'],
  ['month', '달', 'Rent is due every ___ .', '월세는 매달 내야 한다.'],
  ['today', '오늘', 'The test is ___ at noon.', '시험은 오늘 정오다.'],
  ['hour', '시간', 'We waited for an ___ in the rain.', '우리는 빗속에서 한 시간을 기다렸다.'],
  ['minute', '분', 'Wait one ___ , please.', '잠깐만(일 분만) 기다려 주세요.'],
  ['clock', '시계', 'The ___ on the wall stopped.', '벽에 걸린 시계가 멈췄다.'],
  ['early', '이른', 'She woke up ___ this morning.', '그녀는 오늘 아침 일찍 일어났다.'],
  ['late', '늦은', 'He was ___ for the meeting.', '그는 회의에 늦었다.'],
  ['always', '항상', 'He ___ arrives before nine.', '그는 항상 아홉 시 전에 도착한다.'],
  ['never', '결코 ~않다', 'She ___ eats meat.', '그녀는 결코 고기를 먹지 않는다.'],
  ['often', '자주', 'We ___ meet on Fridays.', '우리는 금요일마다 자주 만난다.'],
  ['quick', '빠른', 'He gave a ___ answer.', '그는 빠른 대답을 했다.'],
  ['strong', '강한', 'The wind was very ___ .', '바람이 매우 강했다.'],
  ['weak', '약한', 'The signal here is too ___ .', '여기 신호가 너무 약하다.'],
  ['brave', '용감한', 'The ___ boy saved the puppy.', '그 용감한 소년이 강아지를 구했다.'],
  ['afraid', '두려운', 'She is ___ of tall places.', '그녀는 높은 곳을 두려워한다.'],
  ['lonely', '외로운', 'He felt ___ in the new city.', '그는 새로운 도시에서 외로움을 느꼈다.'],
  ['proud', '자랑스러운', 'Her parents are very ___ .', '그녀의 부모님은 매우 자랑스러워하신다.'],
  ['polite', '예의 바른', 'He is always ___ to guests.', '그는 손님들에게 항상 예의 바르다.'],
  ['rude', '무례한', 'That comment was quite ___ .', '그 말은 꽤 무례했다.'],
  ['honest', '정직한', 'She gave an ___ opinion.', '그녀는 정직한 의견을 말했다.'],
  ['clever', '영리한', 'That was a ___ solution.', '그것은 영리한 해결책이었다.'],
  ['simple', '단순한', 'The recipe is very ___ .', '그 조리법은 매우 단순하다.'],
  ['famous', '유명한', 'He is a ___ painter.', '그는 유명한 화가이다.'],
  ['modern', '현대의', 'They live in a ___ apartment.', '그들은 현대식 아파트에 산다.'],
  ['ancient', '고대의', 'We visited an ___ temple.', '우리는 고대 사원을 방문했다.'],
  ['future', '미래', 'Nobody knows the ___ .', '아무도 미래를 알지 못한다.'],
  ['past', '과거', 'Do not dwell on the ___ .', '과거에 머물러 있지 마라.'],
  ['begin', '시작하다', 'The class will ___ shortly.', '수업이 곧 시작될 것이다.'],
  ['finish', '끝내다', 'Please ___ your homework first.', '숙제를 먼저 끝내세요.'],
  ['change', '바꾸다', 'We must ___ the schedule.', '우리는 일정을 바꿔야 한다.'],
  ['choose', '고르다', 'You may ___ any seat.', '아무 자리나 골라도 된다.'],
  ['decide', '결정하다', 'They will ___ tomorrow.', '그들은 내일 결정할 것이다.'],
  ['fail', '실패하다', 'Do not be afraid to ___ .', '실패하는 것을 두려워하지 마라.'],
  ['leave', '떠나다', 'We ___ for Busan at dawn.', '우리는 새벽에 부산으로 떠난다.'],
  ['arrive', '도착하다', 'They will ___ before noon.', '그들은 정오 전에 도착할 것이다.'],
  ['return', '돌아오다', 'She will ___ next Monday.', '그녀는 다음 월요일에 돌아올 것이다.'],
  ['follow', '따라가다', 'Please ___ the guide closely.', '가이드를 가까이 따라가세요.'],
  ['visit', '방문하다', 'We ___ our grandmother weekly.', '우리는 매주 할머니를 방문한다.'],
  ['invite', '초대하다', 'They will ___ all the neighbors.', '그들은 모든 이웃을 초대할 것이다.'],
  ['thank', '감사하다', 'I want to ___ you sincerely.', '진심으로 당신께 감사드리고 싶습니다.'],
  ['sorry', '미안한', 'He looked truly ___ .', '그는 정말 미안해 보였다.'],
  ['doctor', '의사', 'The ___ examined my throat.', '의사가 내 목을 진찰했다.'],
  ['nurse', '간호사', 'A kind ___ helped the patient.', '친절한 간호사가 환자를 도와주었다.'],
  ['farmer', '농부', 'The ___ grows rice and beans.', '그 농부는 쌀과 콩을 재배한다.'],
  ['artist', '예술가', 'That ___ paints beautiful skies.', '그 예술가는 아름다운 하늘을 그린다.'],
  ['writer', '작가', 'She is a young ___ .', '그녀는 젊은 작가이다.'],
  ['singer', '가수', 'The ___ has a lovely voice.', '그 가수는 아름다운 목소리를 가졌다.'],
  ['driver', '운전사', 'The bus ___ waved at us.', '버스 운전사가 우리에게 손을 흔들었다.'],
  ['police', '경찰', 'The ___ arrived within minutes.', '경찰이 몇 분 안에 도착했다.'],
  ['office', '사무실', 'His ___ is on the third floor.', '그의 사무실은 삼 층에 있다.'],
  ['company', '회사', 'She works for a small ___ .', '그녀는 작은 회사에서 일한다.'],
  ['job', '직업', 'He found a new ___ downtown.', '그는 시내에서 새 직업을 구했다.'],
  ['work', '일하다', 'They ___ from home on Fridays.', '그들은 금요일마다 재택근무를 한다.'],
  ['meeting', '회의', 'The ___ starts at ten.', '회의는 열 시에 시작한다.'],
  ['report', '보고서', 'Please submit your ___ today.', '오늘 보고서를 제출해 주세요.'],
  ['plan', '계획', 'We made a careful ___ .', '우리는 신중한 계획을 세웠다.'],
  ['idea', '생각', 'That is a wonderful ___ .', '그것은 훌륭한 생각이다.'],
  ['problem', '문제', 'We solved the ___ together.', '우리는 함께 그 문제를 해결했다.'],
  ['reason', '이유', 'Give me one good ___ .', '타당한 이유를 하나 대 봐라.'],
  ['result', '결과', 'The ___ surprised everyone.', '그 결과는 모두를 놀라게 했다.'],
  ['story', '이야기', 'Grandmother told a long ___ .', '할머니는 긴 이야기를 들려주셨다.'],
  ['news', '소식', 'The ___ spread quickly.', '그 소식은 빠르게 퍼졌다.'],
  ['picture', '그림', 'Hang the ___ above the sofa.', '소파 위에 그림을 걸어라.'],
  ['film', '영화', 'That ___ won many awards.', '그 영화는 많은 상을 받았다.'],
  ['game', '게임', 'The ___ lasted three hours.', '그 경기는 세 시간 동안 계속됐다.'],
  ['sport', '운동', 'Swimming is a healthy ___ .', '수영은 건강한 운동이다.'],
  ['team', '팀', 'Our ___ won the final match.', '우리 팀이 결승전에서 이겼다.'],
  ['player', '선수', 'The young ___ scored twice.', '그 젊은 선수는 두 골을 넣었다.'],
  ['health', '건강', 'Sleep is vital for good ___ .', '수면은 건강에 필수적이다.'],
  ['body', '몸', 'Exercise keeps the ___ strong.', '운동은 몸을 튼튼하게 유지시켜 준다.'],
  ['heart', '심장', 'His ___ beat quickly.', '그의 심장이 빠르게 뛰었다.'],
  ['hand', '손', 'She raised her right ___ .', '그녀는 오른손을 들었다.'],
  ['voice', '목소리', 'Her ___ was soft and clear.', '그녀의 목소리는 부드럽고 또렷했다.'],
  ['face', '얼굴', 'A smile lit up his ___ .', '미소가 그의 얼굴을 밝게 만들었다.'],
  ['weather', '날씨', 'The ___ turned cold suddenly.', '날씨가 갑자기 추워졌다.'],
  ['cloud', '구름', 'A dark ___ covered the sun.', '어두운 구름이 태양을 가렸다.'],
  ['storm', '폭풍', 'The ___ broke many branches.', '폭풍이 많은 나뭇가지를 부러뜨렸다.'],
  ['light', '빛', 'The ___ from the lamp was dim.', '램프에서 나오는 빛이 희미했다.'],
  ['shadow', '그림자', 'His ___ stretched across the road.', '그의 그림자가 길게 도로를 가로질렀다.'],
  ['fire', '불', 'They sat around the warm ___ .', '그들은 따뜻한 불 주위에 둘러앉았다.'],
  ['stone', '돌', 'He picked up a smooth ___ .', '그는 매끄러운 돌을 집어 들었다.'],
  ['metal', '금속', 'The gate is made of ___ .', '그 문은 금속으로 만들어졌다.'],
  ['paper', '종이', 'Write it on this ___ .', '이 종이에 그것을 적어라.'],
  ['wood', '나무', 'The table is solid ___ .', '그 탁자는 단단한 나무로 되어 있다.'],
  ['jacket', '재킷', 'Wear a warm ___ outside.', '밖에서는 따뜻한 재킷을 입어라.'],
  ['shoes', '신발', 'These ___ are too tight.', '이 신발은 너무 꽉 낀다.'],
  ['pocket', '주머니', 'The key is in my ___ .', '열쇠는 내 주머니 안에 있다.'],
  ['mirror', '거울', 'She looked in the ___ .', '그녀는 거울을 들여다봤다.'],
  ['candle', '초', 'A single ___ lit the room.', '초 하나가 방을 밝혔다.'],
  ['blanket', '담요', 'Pull the ___ over you.', '담요를 몸 위로 끌어당겨라.'],
  ['pillow', '베개', 'This ___ is very soft.', '이 베개는 아주 부드럽다.'],
  ['ladder', '사다리', 'He climbed the wooden ___ .', '그는 나무 사다리를 올라갔다.'],
  ['hammer', '망치', 'Pass me the heavy ___ .', '그 무거운 망치를 건네줘.'],
  ['egg', '달걀', 'She boiled an ___ for breakfast.', '그녀는 아침으로 달걀을 삶았다.'],
  ['milk', '우유', 'He drinks ___ every morning.', '그는 매일 아침 우유를 마신다.'],
  ['juice', '주스', 'I squeezed fresh orange ___ .', '나는 신선한 오렌지 주스를 짰다.'],
  ['fruit', '과일', 'This basket has fresh ___ .', '이 바구니에는 신선한 과일이 있다.'],
  ['grape', '포도', 'She ate a bunch of ___ s.', '그녀는 포도 한 송이를 먹었다.'],
  ['lemon', '레몬', 'Add a slice of ___ to the tea.', '차에 레몬 한 조각을 넣어라.'],
  ['banana', '바나나', 'He peeled a ripe ___ .', '그는 잘 익은 바나나 껍질을 벗겼다.'],
  ['potato', '감자', 'We boiled a big ___ .', '우리는 큰 감자를 삶았다.'],
  ['onion', '양파', 'Chop the ___ finely.', '양파를 잘게 다져라.'],
  ['tomato', '토마토', 'Slice the red ___ .', '빨간 토마토를 썰어라.'],
  ['carrot', '당근', 'Rabbits love to eat ___ s.', '토끼는 당근 먹는 것을 좋아한다.'],
  ['rice', '쌀', 'We eat ___ every day.', '우리는 매일 쌀밥을 먹는다.'],
  ['soup', '수프', 'She made hot ___ for dinner.', '그녀는 저녁으로 뜨거운 수프를 만들었다.'],
  ['cake', '케이크', 'They baked a birthday ___ .', '그들은 생일 케이크를 구웠다.'],
  ['candy', '사탕', 'The child asked for ___ .', '그 아이는 사탕을 달라고 했다.'],
  ['snack', '간식', 'He had a small ___ before bed.', '그는 자기 전에 가벼운 간식을 먹었다.'],
  ['jam', '잼', 'Spread ___ on the toast.', '토스트에 잼을 발라라.'],
  ['honey', '꿀', 'Bees make sweet ___ .', '벌은 달콤한 꿀을 만든다.'],
  ['cream', '크림', 'Add a spoon of ___ .', '크림 한 스푼을 추가해라.'],
  ['toast', '토스트', 'She burned the ___ again.', '그녀는 토스트를 또 태웠다.'],
  ['cereal', '시리얼', 'He eats ___ every morning.', '그는 매일 아침 시리얼을 먹는다.'],
  ['snake', '뱀', 'A ___ crossed the path.', '뱀 한 마리가 길을 가로질렀다.'],
  ['bird', '새', 'A small ___ sang outside.', '작은 새가 밖에서 노래했다.'],
  ['fish', '물고기', 'The ___ swam upstream.', '그 물고기는 상류로 헤엄쳤다.'],
  ['horse', '말', 'He rides a brown ___ .', '그는 갈색 말을 탄다.'],
  ['sheep', '양', 'The ___ grazed on the hill.', '양이 언덕에서 풀을 뜯었다.'],
  ['goat', '염소', 'A ___ ate the flowers.', '염소가 꽃을 먹어치웠다.'],
  ['spider', '거미', 'A ___ spun a web.', '거미가 거미줄을 쳤다.'],
  ['insect', '곤충', 'That ___ has six legs.', '저 곤충은 다리가 여섯 개다.'],
  ['rabbit', '토끼', 'The ___ hopped away quickly.', '토끼는 빠르게 뛰어 도망쳤다.'],
  ['turtle', '거북이', 'The ___ moved very slowly.', '거북이는 아주 천천히 움직였다.'],
  ['monkey', '원숭이', 'A ___ climbed the tree.', '원숭이가 나무를 올랐다.'],
  ['tiger', '호랑이', 'The ___ roared loudly.', '호랑이가 크게 포효했다.'],
  ['bear', '곰', 'A ___ crossed the road.', '곰 한 마리가 길을 건넜다.'],
  ['wolf', '늑대', 'A ___ howled at the moon.', '늑대가 달을 향해 울부짖었다.'],
  ['duck', '오리', 'The ___ swam across the pond.', '오리가 연못을 가로질러 헤엄쳤다.'],
  ['chick', '병아리', 'A ___ followed the hen.', '병아리가 암탉을 따라갔다.'],
  ['dragon', '용', 'The story features a fierce ___ .', '그 이야기에는 사나운 용이 나온다.'],
  ['season', '계절', 'Autumn is my favorite ___ .', '가을은 내가 가장 좋아하는 계절이다.'],
  ['puddle', '웅덩이', 'She jumped over a ___ .', '그녀는 웅덩이를 뛰어넘었다.'],
  ['desert', '사막', 'It rarely rains in the ___ .', '그 사막에는 비가 거의 오지 않는다.'],
  ['valley', '계곡', 'A river runs through the ___ .', '강이 그 계곡을 가로질러 흐른다.'],
  ['jungle', '정글', 'Tigers live in the ___ .', '호랑이는 정글에 산다.'],
  ['cave', '동굴', 'They explored a dark ___ .', '그들은 어두운 동굴을 탐험했다.'],
  ['rock', '바위', 'A large ___ blocked the path.', '큰 바위가 길을 막았다.'],
  ['sand', '모래', 'Children played in the ___ .', '아이들은 모래에서 놀았다.'],
  ['wave', '파도', 'A big ___ hit the boat.', '큰 파도가 배를 덮쳤다.'],
  ['star', '별', 'A bright ___ appeared at dusk.', '해 질 녘에 밝은 별이 나타났다.'],
  ['moon', '달', 'The ___ was full last night.', '어젯밤은 보름달이었다.'],
  ['sky', '하늘', 'The ___ turned orange at sunset.', '하늘이 해 질 무렵 주황빛으로 물들었다.'],
  ['rain', '비', 'Heavy ___ fell all night.', '밤새 폭우가 내렸다.'],
  ['snow', '눈', 'Soft ___ covered the roof.', '부드러운 눈이 지붕을 덮었다.'],
  ['wind', '바람', 'A cold ___ blew from the north.', '북쪽에서 찬바람이 불었다.'],
  ['ice', '얼음', 'The pond froze into solid ___ .', '연못이 단단한 얼음으로 얼었다.'],
  ['sun', '태양', 'The ___ rose over the hills.', '태양이 언덕 위로 떠올랐다.'],
  ['flag', '깃발', 'The ___ waved in the wind.', '깃발이 바람에 나부꼈다.'],
  ['bell', '종', 'The school ___ rang loudly.', '학교 종이 크게 울렸다.'],
  ['drum', '북', 'He played the ___ with energy.', '그는 힘차게 북을 연주했다.'],
  ['piano', '피아노', 'She practices ___ every day.', '그녀는 매일 피아노를 연습한다.'],
  ['guitar', '기타', 'He learned to play the ___ .', '그는 기타 연주를 배웠다.'],
  ['violin', '바이올린', 'The girl plays the ___ well.', '그 소녀는 바이올린을 잘 켠다.'],
  ['ball', '공', 'The kids kicked the ___ around.', '아이들은 공을 발로 찼다.'],
  ['toy', '장난감', 'The boy shared his ___ .', '그 소년은 자신의 장난감을 나눠 주었다.'],
  ['doll', '인형', 'She sewed clothes for her ___ .', '그녀는 인형 옷을 만들었다.'],
  ['puzzle', '퍼즐', 'They solved the ___ together.', '그들은 함께 퍼즐을 풀었다.'],
  ['pencil', '연필', 'He sharpened his ___ .', '그는 연필을 깎았다.'],
  ['eraser', '지우개', 'May I borrow your ___ ?', '지우개 좀 빌려줄 수 있니?'],
  ['ruler', '자', 'Use a ___ to draw a line.', '선을 그으려면 자를 사용해라.'],
  ['crayon', '크레용', 'The child colored with a ___ .', '그 아이는 크레용으로 색칠했다.'],
  ['desk', '책상', 'Her ___ was covered in books.', '그녀의 책상은 책으로 뒤덮여 있었다.'],
  ['shelf', '선반', 'Put the box on the top ___ .', '상자를 맨 위 선반에 올려라.'],
  ['stairs', '계단', 'She ran up the ___ quickly.', '그녀는 계단을 빠르게 뛰어올랐다.'],
  ['floor', '바닥', 'The ___ was cold this morning.', '오늘 아침 바닥이 차가웠다.'],
  ['roof', '지붕', 'Snow piled up on the ___ .', '눈이 지붕 위에 쌓였다.'],
  ['wall', '벽', 'They painted the ___ blue.', '그들은 벽을 파란색으로 칠했다.'],
  ['door', '문', 'Please close the ___ quietly.', '문을 조용히 닫아 주세요.'],
  ['yard', '마당', 'The dog played in the ___ .', '개가 마당에서 놀았다.'],
  ['fence', '울타리', 'A wooden ___ surrounds the yard.', '나무 울타리가 마당을 둘러싸고 있다.'],
  ['gate', '대문', 'He locked the front ___ .', '그는 정문을 잠갔다.'],
  ['stove', '스토브', 'She cooked rice on the ___ .', '그녀는 스토브에서 밥을 지었다.'],
  ['oven', '오븐', 'The bread is baking in the ___ .', '빵이 오븐에서 구워지고 있다.'],
  ['fridge', '냉장고', 'Put the milk in the ___ .', '우유를 냉장고에 넣어라.'],
  ['towel', '수건', 'Dry your hands with a ___ .', '수건으로 손을 말려라.'],
  ['soap', '비누', 'Wash your hands with ___ .', '비누로 손을 씻어라.'],
  ['brush', '솔', 'He cleaned his shoes with a ___ .', '그는 솔로 신발을 닦았다.'],
  ['comb', '빗', 'She used a ___ on her hair.', '그녀는 머리를 빗에 빗었다.'],
  ['bath', '목욕', 'The baby loves ___ time.', '아기는 목욕 시간을 좋아한다.'],
  ['razor', '면도기', 'He shaved with a sharp ___ .', '그는 날카로운 면도기로 면도했다.'],
  ['collar', '옷깃', 'His shirt ___ was too tight.', '그의 셔츠 옷깃이 너무 조였다.'],
  ['button', '단추', 'A ___ fell off his shirt.', '그의 셔츠에서 단추 하나가 떨어졌다.'],
  ['zipper', '지퍼', 'The ___ on my bag broke.', '내 가방 지퍼가 고장 났다.'],
  ['scarf', '목도리', 'She wrapped a warm ___ around her neck.', '그녀는 목에 따뜻한 목도리를 둘렀다.'],
  ['glove', '장갑', 'He wore a thick ___ to garden.', '그는 정원 일을 하려고 두꺼운 장갑을 꼈다.'],
  ['dress', '드레스', 'She wore a blue ___ .', '그녀는 파란 드레스를 입었다.'],
  ['skirt', '치마', 'The girl wore a red ___ .', '그 소녀는 빨간 치마를 입었다.'],
  ['pants', '바지', 'These ___ are too long.', '이 바지는 너무 길다.'],
  ['boots', '부츠', 'He wore muddy ___ .', '그는 진흙 묻은 부츠를 신었다.'],
  ['sock', '양말', 'One ___ went missing.', '양말 한 짝이 사라졌다.'],
  ['belt', '벨트', 'He tightened his leather ___ .', '그는 가죽 벨트를 졸라맸다.'],
  ['hat', '모자', 'She wore a straw ___ .', '그녀는 밀짚모자를 썼다.'],
  ['crown', '왕관', 'The king wore a golden ___ .', '왕은 황금 왕관을 썼다.'],
  ['ring', '반지', 'She lost her wedding ___ .', '그녀는 결혼반지를 잃어버렸다.'],
  ['chain', '사슬', 'A metal ___ locked the gate.', '금속 사슬이 대문을 잠갔다.'],
  ['string', '끈', 'Tie the box with a ___ .', '끈으로 상자를 묶어라.'],
  ['rope', '밧줄', 'They pulled the boat with a ___ .', '그들은 밧줄로 배를 끌었다.'],
  ['wire', '전선', 'The ___ carries electricity.', '그 전선은 전기를 전달한다.'],
  ['pipe', '파이프', 'Water flows through the ___ .', '물이 파이프를 통해 흐른다.'],
  ['engine', '엔진', 'The car ___ made a strange noise.', '자동차 엔진에서 이상한 소리가 났다.'],
  ['wheel', '바퀴', 'One ___ was flat.', '바퀴 하나가 펑크 났다.'],
  ['brake', '브레이크', 'He hit the ___ suddenly.', '그는 갑자기 브레이크를 밟았다.'],
  ['bicycle', '자전거', 'She rides her ___ to work.', '그녀는 자전거를 타고 출근한다.'],
  ['helmet', '헬멧', 'Always wear a ___ when biking.', '자전거를 탈 때는 항상 헬멧을 써라.'],
  ['screen', '화면', 'The ___ went black suddenly.', '화면이 갑자기 까맣게 변했다.'],
  ['laptop', '노트북', 'She types on her ___ daily.', '그녀는 매일 노트북으로 타자를 친다.'],
  ['camera', '카메라', 'He took a photo with his ___ .', '그는 카메라로 사진을 찍었다.'],
  ['battery', '건전지', 'The remote needs a new ___ .', '리모컨에 새 건전지가 필요하다.'],
  ['switch', '스위치', 'Flip the ___ to turn it on.', '켜려면 스위치를 눌러라.'],
  ['signal', '신호', 'The phone lost its ___ .', '휴대폰이 신호를 잃었다.'],
  ['nation', '국가', 'Every ___ has its own flag.', '모든 국가는 자기만의 국기를 가지고 있다.'],
  ['temple', '사원', 'They visited an old ___ .', '그들은 오래된 사원을 방문했다.'],
  ['castle', '성', 'The ___ stood on the hill.', '그 성은 언덕 위에 서 있었다.'],
  ['palace', '궁전', 'The king lived in a grand ___ .', '왕은 웅장한 궁전에 살았다.'],
  ['statue', '조각상', 'A stone ___ stood in the park.', '돌 조각상이 공원에 서 있었다.'],
  ['museum', '박물관', 'We visited the art ___ .', '우리는 미술 박물관을 방문했다.'],
  ['church', '교회', 'They walked to the local ___ .', '그들은 동네 교회까지 걸어갔다.'],
  ['prayer', '기도', 'She said a quiet ___ .', '그녀는 조용히 기도를 올렸다.'],
  ['priest', '사제', 'The ___ blessed the couple.', '사제가 그 부부를 축복했다.'],
  ['heaven', '천국', 'She believes in ___ .', '그녀는 천국을 믿는다.'],
  ['spirit', '영혼', 'His ___ stayed strong.', '그의 영혼은 강인함을 유지했다.'],
  ['ghost', '유령', 'The kids told a ___ story.', '아이들은 유령 이야기를 했다.'],
  ['magic', '마법', 'The trick seemed like ___ .', '그 마술은 마법 같았다.'],
  ['wizard', '마법사', 'The ___ waved his wand.', '마법사가 지팡이를 흔들었다.'],
  ['fairy', '요정', 'A ___ appeared in the tale.', '이야기 속에 요정이 나타났다.'],
  ['prince', '왕자', 'The ___ rode a white horse.', '왕자는 흰 말을 탔다.'],
  ['queen', '여왕', 'The ___ ruled wisely.', '여왕은 현명하게 다스렸다.'],
  ['knight', '기사', 'A brave ___ guarded the gate.', '용감한 기사가 성문을 지켰다.'],
  ['sword', '검', 'He raised his ___ high.', '그는 검을 높이 들었다.'],
  ['shield', '방패', 'The soldier held a metal ___ .', '병사가 금속 방패를 들었다.'],
  ['army', '군대', 'The ___ marched at dawn.', '군대는 새벽에 행진했다.'],
  ['battle', '전투', 'The ___ lasted all day.', '그 전투는 하루 종일 이어졌다.'],
  ['enemy', '적', 'They faced a strong ___ .', '그들은 강한 적과 맞섰다.'],
  ['peace', '평화', 'Both sides wanted ___ .', '양측 모두 평화를 원했다.'],
  ['border', '국경', 'They crossed the ___ safely.', '그들은 안전하게 국경을 넘었다.'],
  ['coast', '해안', 'Waves crashed on the ___ .', '파도가 해안에 부딪혔다.'],
  ['harbor', '항구', 'Ships rested in the ___ .', '배들이 항구에 정박해 있었다.'],
  ['anchor', '닻', 'The sailor dropped the ___ .', '선원이 닻을 내렸다.'],
  ['sailor', '선원', 'The ___ climbed the mast.', '선원이 돛대를 올랐다.'],
  ['pirate', '해적', 'The ___ buried his treasure.', '해적은 보물을 묻었다.'],
  ['gems', '보석', 'The chest held shining ___ .', '그 상자에는 빛나는 보석이 들어 있었다.'],
  ['jewel', '보석', 'The ring held a bright ___ .', '그 반지에는 빛나는 보석이 박혀 있었다.'],
  ['gold', '금', 'The ring is made of ___ .', '그 반지는 금으로 만들어졌다.'],
  ['silver', '은', 'She wore a ___ necklace.', '그녀는 은목걸이를 착용했다.'],
  ['coin', '동전', 'He found an old ___ .', '그는 오래된 동전을 발견했다.'],
  ['wallet', '지갑', 'He lost his leather ___ .', '그는 가죽 지갑을 잃어버렸다.'],
  ['purse', '지갑', 'She kept coins in her ___ .', '그녀는 지갑에 동전을 넣어 두었다.'],
  ['card', '카드', 'She paid with a bank ___ .', '그녀는 은행 카드로 계산했다.'],
  ['gift', '선물', 'He wrapped a birthday ___ .', '그는 생일 선물을 포장했다.'],
  ['prize', '상', 'She won first ___ .', '그녀는 일등 상을 받았다.'],
  ['medal', '메달', 'He earned a gold ___ .', '그는 금메달을 땄다.'],
  ['trophy', '트로피', 'The team lifted the ___ .', '그 팀은 트로피를 들어 올렸다.'],
  ['champ', '챔피언', 'She became the new ___ .', '그녀는 새로운 챔피언이 되었다.'],
  ['race', '경주', 'He won the school ___ .', '그는 학교 경주에서 우승했다.'],
  ['track', '트랙', 'Runners lined up on the ___ .', '주자들이 트랙에 늘어섰다.'],
  ['court', '코트', 'They played on a tennis ___ .', '그들은 테니스 코트에서 경기했다.'],
  ['coach', '코치', 'The ___ trained the team hard.', '코치는 팀을 혹독하게 훈련시켰다.'],
  ['whistle', '호루라기', 'The referee blew his ___ .', '심판이 호루라기를 불었다.'],
  ['stadium', '경기장', 'The ___ was packed with fans.', '경기장은 팬들로 가득 찼다.'],
  ['goal', '골', 'She scored the winning ___ .', '그녀는 결승골을 넣었다.'],
  ['score', '점수', 'The final ___ was two to one.', '최종 점수는 2대 1이었다.'],
  ['victory', '승리', 'The team celebrated their ___ .', '그 팀은 승리를 축하했다.'],
  ['defeat', '패배', 'They accepted the ___ calmly.', '그들은 차분히 패배를 받아들였다.'],
  ['nest', '둥지', 'A bird built a ___ in the tree.', '새가 나무에 둥지를 지었다.'],
  ['feather', '깃털', 'A white ___ fell to the ground.', '하얀 깃털이 땅에 떨어졌다.'],
  ['tail', '꼬리', 'The dog wagged its ___ .', '개가 꼬리를 흔들었다.'],
  ['paw', '발(동물)', 'The cat hurt its front ___ .', '고양이가 앞발을 다쳤다.'],
  ['fur', '털(동물)', 'The rabbit has soft white ___ .', '토끼는 부드러운 흰 털을 가졌다.'],
  ['wing', '날개', 'The bird spread its ___ s.', '그 새는 날개를 펼쳤다.'],
  ['beak', '부리', 'The bird has a sharp ___ .', '그 새는 날카로운 부리를 가졌다.'],
  ['nail', '못', 'He hit the ___ with a hammer.', '그는 망치로 못을 박았다.'],
  ['screw', '나사', 'Tighten the loose ___ .', '헐거운 나사를 조여라.'],
  ['glue', '풀', 'She stuck the paper with ___ .', '그녀는 풀로 종이를 붙였다.'],
  ['tape', '테이프', 'He sealed the box with ___ .', '그는 테이프로 상자를 봉했다.'],
  ['blade', '날', 'The knife ___ was very sharp.', '그 칼날은 매우 날카로웠다.'],
  ['needle', '바늘', 'She threaded the ___ carefully.', '그녀는 조심스럽게 바늘에 실을 꿰었다.'],
  ['thread', '실', 'The ___ snapped suddenly.', '실이 갑자기 끊어졌다.'],
  ['cloth', '천', 'Wipe the table with a damp ___ .', '젖은 천으로 탁자를 닦아라.'],
  ['silk', '비단', 'She wore a smooth ___ scarf.', '그녀는 매끄러운 비단 스카프를 둘렀다.'],
  ['cotton', '면', 'This shirt is pure ___ .', '이 셔츠는 순면이다.'],
  ['leather', '가죽', 'He bought a ___ jacket.', '그는 가죽 재킷을 샀다.'],
  ['brick', '벽돌', 'The wall is made of red ___ .', '그 벽은 붉은 벽돌로 만들어졌다.'],
  ['cement', '시멘트', 'Workers poured wet ___ .', '인부들이 젖은 시멘트를 부었다.'],
  ['dust', '먼지', 'A layer of ___ covered the shelf.', '먼지 한 겹이 선반을 덮고 있었다.'],
  ['mud', '진흙', 'His boots were covered in ___ .', '그의 부츠는 진흙투성이였다.'],
  ['fog', '안개', 'Thick ___ covered the road.', '짙은 안개가 도로를 뒤덮었다.'],
  ['thunder', '천둥', 'Loud ___ shook the windows.', '요란한 천둥이 창문을 흔들었다.'],
  ['flash', '번쩍임', 'A ___ of light woke him up.', '번쩍이는 빛이 그를 깨웠다.'],
  ['rainbow', '무지개', 'A ___ appeared after the rain.', '비가 그친 후 무지개가 나타났다.'],
  ['breeze', '산들바람', 'A gentle ___ cooled the park.', '산들바람이 공원을 시원하게 했다.'],
  ['label', '라벨', 'Check the price ___ first.', '먼저 가격표를 확인해라.'],
  ['recipe', '조리법', 'She followed the ___ exactly.', '그녀는 조리법을 정확히 따랐다.'],
]

/* ------------------------------------------------------------------
   중급 — 12글자 이하. 글이나 대화에서 자주 만나는 말들.
   ------------------------------------------------------------------ */
const normal = [
  ['breakfast', '아침 식사', 'Never skip ___ before a long day.', '긴 하루를 앞두고는 절대 아침 식사를 거르지 마라.'],
  ['mountain', '산', 'They hiked up the steep ___ .', '그들은 가파른 산을 올랐다.'],
  ['remember', '기억하다', 'I still ___ her kind words.', '나는 아직도 그녀의 다정한 말을 기억한다.'],
  ['tomorrow', '내일', 'The results arrive ___ morning.', '결과는 내일 아침에 나온다.'],
  ['beautiful', '아름다운', 'The sunset was truly ___ .', '그 노을은 정말 아름다웠다.'],
  ['dangerous', '위험한', 'That road is ___ at night.', '그 길은 밤에 위험하다.'],
  ['difficult', '어려운', 'The exam was quite ___ .', '그 시험은 꽤 어려웠다.'],
  ['important', '중요한', 'Rest is ___ for recovery.', '회복에는 휴식이 중요하다.'],
  ['necessary', '필요한', 'A visa is ___ for that trip.', '그 여행에는 비자가 필요하다.'],
  ['possible', '가능한', 'It is ___ to finish today.', '오늘 끝내는 것도 가능하다.'],
  ['knowledge', '지식', 'She shared her ___ generously.', '그녀는 자신의 지식을 아낌없이 나눠 주었다.'],
  ['education', '교육', 'Good ___ opens many doors.', '좋은 교육은 많은 기회의 문을 연다.'],
  ['community', '공동체', 'The ___ raised funds quickly.', '그 공동체는 빠르게 기금을 모았다.'],
  ['agreement', '합의', 'They reached an ___ at last.', '그들은 마침내 합의에 이르렀다.'],
  ['argument', '논쟁', 'The ___ lasted all evening.', '그 논쟁은 저녁 내내 이어졌다.'],
  ['decision', '결정', 'It was a difficult ___ .', '그것은 어려운 결정이었다.'],
  ['direction', '방향', 'We walked in the wrong ___ .', '우리는 잘못된 방향으로 걸었다.'],
  ['election', '선거', 'The ___ was held peacefully.', '그 선거는 평화롭게 치러졌다.'],
  ['emotion', '감정', 'His voice showed real ___ .', '그의 목소리에는 진짜 감정이 담겨 있었다.'],
  ['attention', '주의', 'Please pay close ___ .', '주의 깊게 집중해 주세요.'],
  ['solution', '해결책', 'We found a simple ___ .', '우리는 간단한 해결책을 찾았다.'],
  ['question', '질문', 'That is an excellent ___ .', '그것은 훌륭한 질문이다.'],
  ['position', '위치', 'Move the lamp to that ___ .', '램프를 그 위치로 옮겨라.'],
  ['condition', '상태', 'The car is in fine ___ .', '그 차는 좋은 상태다.'],
  ['situation', '상황', 'The ___ improved slowly.', '상황이 서서히 나아졌다.'],
  ['tradition', '전통', 'This ___ dates back centuries.', '이 전통은 수백 년 전으로 거슬러 올라간다.'],
  ['culture', '문화', 'Food reveals a lot about ___ .', '음식은 문화에 대해 많은 것을 보여 준다.'],
  ['history', '역사', 'She teaches Korean ___ .', '그녀는 한국 역사를 가르친다.'],
  ['science', '과학', 'Modern ___ advances rapidly.', '현대 과학은 빠르게 발전한다.'],
  ['research', '연구', 'His ___ took five years.', '그의 연구는 오 년이 걸렸다.'],
  ['evidence', '증거', 'The ___ was convincing.', '그 증거는 설득력이 있었다.'],
  ['theory', '이론', 'That ___ is widely accepted.', '그 이론은 널리 받아들여진다.'],
  ['method', '방법', 'We tried a different ___ .', '우리는 다른 방법을 시도했다.'],
  ['process', '과정', 'The ___ takes several weeks.', '그 과정은 몇 주가 걸린다.'],
  ['progress', '진전', 'She made steady ___ .', '그녀는 꾸준한 진전을 이뤘다.'],
  ['purpose', '목적', 'What is the ___ of this rule?', '이 규칙의 목적은 무엇인가?'],
  ['benefit', '이익', 'Exercise has a clear ___ .', '운동에는 분명한 이익이 있다.'],
  ['advantage', '장점', 'Speed is our main ___ .', '속도는 우리의 주된 장점이다.'],
  ['disadvantage', '단점', 'Cost is the main ___ .', '비용이 주된 단점이다.'],
  ['challenge', '도전', 'The project was a real ___ .', '그 프로젝트는 진짜 도전이었다.'],
  ['opinion', '의견', 'I respect your ___ .', '나는 당신의 의견을 존중한다.'],
  ['suggestion', '제안', 'Thank you for the ___ .', '제안해 주셔서 감사합니다.'],
  ['statement', '진술', 'He signed the written ___ .', '그는 서면 진술서에 서명했다.'],
  ['announcement', '발표', 'The ___ came this morning.', '그 발표는 오늘 아침에 나왔다.'],
  ['conversation', '대화', 'We had a long ___ .', '우리는 긴 대화를 나눴다.'],
  ['discussion', '토론', 'The ___ grew heated.', '그 토론은 뜨거워졌다.'],
  ['description', '묘사', 'Her ___ was very vivid.', '그녀의 묘사는 매우 생생했다.'],
  ['instruction', '지시', 'Follow each ___ carefully.', '각 지시를 주의 깊게 따르세요.'],
  ['requirement', '요건', 'Experience is a strict ___ .', '경력은 엄격한 요건이다.'],
  ['equipment', '장비', 'The ___ arrived yesterday.', '그 장비는 어제 도착했다.'],
  ['material', '재료', 'Choose a lighter ___ .', '더 가벼운 재료를 골라라.'],
  ['product', '제품', 'This ___ sells very well.', '이 제품은 아주 잘 팔린다.'],
  ['industry', '산업', 'The film ___ is growing.', '영화 산업이 성장하고 있다.'],
  ['business', '사업', 'Their ___ expanded abroad.', '그들의 사업은 해외로 확장했다.'],
  ['customer', '고객', 'Every ___ deserves respect.', '모든 고객은 존중받을 자격이 있다.'],
  ['service', '서비스', 'The ___ here is excellent.', '이곳의 서비스는 훌륭하다.'],
  ['quality', '품질', 'We never compromise on ___ .', '우리는 품질에서 절대 타협하지 않는다.'],
  ['quantity', '양', 'Order a smaller ___ .', '더 적은 양을 주문해라.'],
  ['increase', '증가하다', 'Prices will ___ next month.', '가격이 다음 달에 오를 것이다.'],
  ['decrease', '감소하다', 'Sales began to ___ slowly.', '매출이 서서히 줄기 시작했다.'],
  ['develop', '개발하다', 'They ___ new software.', '그들은 새 소프트웨어를 개발한다.'],
  ['improve', '개선하다', 'She wants to ___ her writing.', '그녀는 자신의 글쓰기를 개선하고 싶어 한다.'],
  ['provide', '제공하다', 'We ___ free training.', '우리는 무료 교육을 제공한다.'],
  ['produce', '생산하다', 'This farm can ___ enough rice.', '이 농장은 충분한 쌀을 생산할 수 있다.'],
  ['consider', '고려하다', 'Please ___ my request.', '제 요청을 고려해 주세요.'],
  ['continue', '계속하다', 'They will ___ the search.', '그들은 수색을 계속할 것이다.'],
  ['complete', '완성하다', 'Please ___ the form.', '양식을 완성해 주세요.'],
  ['prepare', '준비하다', 'We must ___ for the storm.', '우리는 폭풍에 대비해야 한다.'],
  ['discover', '발견하다', 'Scientists ___ new species yearly.', '과학자들은 매년 새로운 종을 발견한다.'],
  ['describe', '묘사하다', 'Can you ___ the man?', '그 남자를 묘사해 줄 수 있니?'],
  ['explain', '설명하다', 'Let me ___ the rule again.', '그 규칙을 다시 설명해 줄게.'],
  ['express', '표현하다', 'She struggled to ___ her feelings.', '그녀는 자신의 감정을 표현하기 힘들어했다.'],
  ['suggest', '제안하다', 'I ___ we leave early.', '나는 일찍 떠나는 것을 제안한다.'],
  ['recommend', '추천하다', 'Doctors ___ regular exercise.', '의사들은 규칙적인 운동을 추천한다.'],
  ['announce', '발표하다', 'They will ___ the winner soon.', '그들은 곧 우승자를 발표할 것이다.'],
  ['achieve', '달성하다', 'He hopes to ___ his goal.', '그는 목표를 달성하기를 바란다.'],
  ['succeed', '성공하다', 'She worked hard to ___ .', '그녀는 성공하기 위해 열심히 노력했다.'],
  ['prevent', '예방하다', 'Vaccines ___ many illnesses.', '백신은 많은 질병을 예방한다.'],
  ['protect', '보호하다', 'Trees ___ the soil.', '나무는 토양을 보호한다.'],
  ['support', '지지하다', 'Many people ___ the plan.', '많은 사람들이 그 계획을 지지한다.'],
  ['require', '요구하다', 'These plants ___ little water.', '이 식물들은 물을 거의 요구하지 않는다.'],
  ['include', '포함하다', 'Does the price ___ tax?', '가격에 세금이 포함되나요?'],
  ['contain', '담고 있다', 'This box may ___ glass.', '이 상자에는 유리가 들어 있을 수 있다.'],
  ['reduce', '줄이다', 'We must ___ our waste.', '우리는 쓰레기를 줄여야 한다.'],
  ['replace', '대체하다', 'Please ___ the broken part.', '고장 난 부품을 교체해 주세요.'],
  ['repair', '수리하다', 'He can ___ old clocks.', '그는 오래된 시계를 수리할 수 있다.'],
  ['measure', '측정하다', 'Please ___ the room first.', '먼저 방 크기를 측정해 주세요.'],
  ['compare', '비교하다', 'Let us ___ the two plans.', '두 계획을 비교해 보자.'],
  ['connect', '연결하다', 'This road will ___ both towns.', '이 도로는 두 마을을 연결할 것이다.'],
  ['separate', '분리하다', 'Please ___ the paper and plastic.', '종이와 플라스틱을 분리해 주세요.'],
  ['organize', '조직하다', 'She will ___ the event.', '그녀가 그 행사를 조직할 것이다.'],
  ['manage', '관리하다', 'He can ___ a large team.', '그는 큰 팀을 관리할 수 있다.'],
  ['control', '통제하다', 'Try to ___ your temper.', '화를 다스리려고 노력해라.'],
  ['operate', '운영하다', 'They ___ three factories.', '그들은 공장 세 곳을 운영한다.'],
  ['maintain', '유지하다', 'We must ___ these standards.', '우리는 이 기준을 유지해야 한다.'],
  ['establish', '설립하다', 'They plan to ___ a school.', '그들은 학교를 설립할 계획이다.'],
  ['introduce', '소개하다', 'Let me ___ my colleague.', '제 동료를 소개할게요.'],
  ['influence', '영향', 'Her ___ on the team was huge.', '팀에 대한 그녀의 영향은 컸다.'],
  ['pressure', '압력', 'He works well under ___ .', '그는 압박 속에서도 일을 잘한다.'],
  ['balance', '균형', 'Find a ___ between work and rest.', '일과 휴식 사이의 균형을 찾아라.'],
  ['distance', '거리', 'The ___ is about ten kilometers.', '그 거리는 약 십 킬로미터다.'],
  ['surface', '표면', 'The ___ felt rough.', '그 표면은 거칠게 느껴졌다.'],
  ['structure', '구조', 'The ___ needs repair.', '그 구조물은 보수가 필요하다.'],
  ['pattern', '무늬', 'The cloth has a floral ___ .', '그 천에는 꽃무늬가 있다.'],
  ['feature', '특징', 'Its best ___ is the screen.', '그것의 가장 좋은 특징은 화면이다.'],
  ['element', '요소', 'Trust is a key ___ .', '신뢰는 핵심 요소이다.'],
  ['factor', '요인', 'Cost was the deciding ___ .', '비용이 결정적인 요인이었다.'],
  ['effect', '효과', 'The medicine had a quick ___ .', '그 약은 빠른 효과가 있었다.'],
  ['impact', '충격', 'The news had a strong ___ .', '그 소식은 큰 충격을 주었다.'],
  ['growth', '성장', 'Steady ___ continued all year.', '꾸준한 성장이 일 년 내내 이어졌다.'],
  ['success', '성공', 'Her ___ inspired many.', '그녀의 성공은 많은 이들에게 영감을 주었다.'],
  ['failure', '실패', 'The ___ taught us a lot.', '그 실패는 우리에게 많은 것을 가르쳐 주었다.'],
  ['mistake', '실수', 'Everyone makes a ___ sometimes.', '누구나 가끔 실수를 한다.'],
  ['accident', '사고', 'The ___ blocked the road.', '그 사고로 도로가 막혔다.'],
  ['danger', '위험', 'The sign warns of ___ .', '그 표지판은 위험을 경고한다.'],
  ['safety', '안전', 'Wear a helmet for your ___ .', '안전을 위해 헬멧을 착용해라.'],
  ['risk', '위험 부담', 'Every choice carries some ___ .', '모든 선택에는 어느 정도의 위험 부담이 따른다.'],
  ['chance', '기회', 'Give him another ___ .', '그에게 한 번 더 기회를 줘라.'],
  ['opportunity', '기회', 'This is a rare ___ .', '이것은 드문 기회다.'],
  ['ability', '능력', 'She has real ___ in math.', '그녀는 수학에 진짜 능력이 있다.'],
  ['skill', '기술', 'Cooking is a useful ___ .', '요리는 유용한 기술이다.'],
  ['talent', '재능', 'He shows great musical ___ .', '그는 뛰어난 음악적 재능을 보인다.'],
  ['effort', '노력', 'Your ___ finally paid off.', '너의 노력이 마침내 결실을 맺었다.'],
  ['practice', '연습', 'Daily ___ makes a difference.', '매일의 연습이 차이를 만든다.'],
  ['experience', '경험', 'Her ___ helped the team.', '그녀의 경험이 팀에 도움이 됐다.'],
  ['memory', '기억', 'That song brings back a ___ .', '그 노래는 어떤 기억을 떠올리게 한다.'],
  ['attitude', '태도', 'His ___ improved quickly.', '그의 태도가 빠르게 나아졌다.'],
  ['behavior', '행동', 'Her ___ surprised us.', '그녀의 행동은 우리를 놀라게 했다.'],
  ['character', '성격', 'He has a gentle ___ .', '그는 온화한 성격을 가졌다.'],
  ['personal', '개인의', 'That is a ___ matter.', '그것은 개인적인 문제다.'],
  ['private', '사적인', 'This is a ___ conversation.', '이것은 사적인 대화이다.'],
  ['public', '공공의', 'The park is open to the ___ .', '그 공원은 대중에게 개방되어 있다.'],
  ['general', '일반적인', 'That is the ___ opinion.', '그것이 일반적인 의견이다.'],
  ['special', '특별한', 'Today is a ___ occasion.', '오늘은 특별한 날이다.'],
  ['similar', '비슷한', 'The twins have ___ voices.', '그 쌍둥이는 비슷한 목소리를 가졌다.'],
  ['different', '다른', 'Their views are quite ___ .', '그들의 견해는 상당히 다르다.'],
  ['various', '다양한', 'We tried ___ approaches.', '우리는 다양한 접근법을 시도했다.'],
  ['certain', '확실한', 'I am ___ he will come.', '나는 그가 올 것이라고 확신한다.'],
  ['obvious', '명백한', 'The answer was ___ .', '그 답은 명백했다.'],
  ['complex', '복잡한', 'The rules are rather ___ .', '그 규칙들은 다소 복잡하다.'],
  ['serious', '심각한', 'This is a ___ problem.', '이것은 심각한 문제다.'],
  ['careful', '조심스러운', 'Be ___ on the wet floor.', '젖은 바닥에서는 조심해라.'],
  ['popular', '인기 있는', 'That song became ___ fast.', '그 노래는 빠르게 인기를 얻었다.'],
  ['natural', '자연의', 'This soap uses ___ oils.', '이 비누는 천연 오일을 사용한다.'],
  ['physical', '신체의', 'Regular ___ activity helps.', '규칙적인 신체 활동은 도움이 된다.'],
  ['mental', '정신의', 'Rest supports ___ health.', '휴식은 정신 건강에 도움이 된다.'],
  ['social', '사회의', 'They study ___ change.', '그들은 사회적 변화를 연구한다.'],
  ['economic', '경제의', 'The ___ outlook improved.', '경제 전망이 나아졌다.'],
  ['political', '정치의', 'It became a ___ issue.', '그것은 정치적 쟁점이 되었다.'],
  ['medical', '의료의', 'He needs ___ attention.', '그는 의료적 처치가 필요하다.'],
  ['legal', '법적인', 'She sought ___ advice.', '그녀는 법적 조언을 구했다.'],
  ['financial', '재정의', 'The ___ report is due.', '재정 보고서 제출 기한이다.'],
  ['available', '이용 가능한', 'No seats are ___ tonight.', '오늘 밤은 이용 가능한 좌석이 없다.'],
  ['suitable', '적합한', 'This film is not ___ for children.', '이 영화는 아이들에게 적합하지 않다.'],
  ['reliable', '믿을 만한', 'He is a ___ partner.', '그는 믿을 만한 동업자다.'],
  ['flexible', '유연한', 'Our schedule is ___ .', '우리 일정은 유연하다.'],
  ['efficient', '효율적인', 'The new system is more ___ .', '새 시스템이 더 효율적이다.'],
  ['effective', '효과적인', 'That method proved ___ .', '그 방법은 효과적임이 입증되었다.'],
  ['accurate', '정확한', 'Her measurements were ___ .', '그녀의 측정값은 정확했다.'],
  ['precise', '정밀한', 'We need a ___ figure.', '우리는 정밀한 수치가 필요하다.'],
  ['approximate', '대략의', 'Give me an ___ number.', '대략적인 숫자를 알려줘.'],
  ['average', '평균의', 'His score was above ___ .', '그의 점수는 평균 이상이었다.'],
  ['maximum', '최대의', 'The ___ speed is eighty.', '최대 속도는 팔십이다.'],
  ['minimum', '최소의', 'There is a ___ order.', '최소 주문 수량이 있다.'],
  ['recent', '최근의', 'A ___ study confirmed it.', '최근 연구가 그것을 확인해 주었다.'],
  ['current', '현재의', 'The ___ rate is low.', '현재 금리는 낮다.'],
  ['previous', '이전의', 'Check the ___ chapter.', '이전 장을 확인해라.'],
  ['following', '다음의', 'Read the ___ passage.', '다음 지문을 읽어라.'],
  ['further', '더 이상의', 'No ___ action is needed.', '더 이상의 조치는 필요 없다.'],
  ['whole', '전체의', 'She read the ___ book.', '그녀는 그 책 전체를 읽었다.'],
  ['entire', '전체의', 'The ___ village celebrated.', '마을 전체가 축하했다.'],
  ['several', '여럿의', 'He asked ___ questions.', '그는 여러 질문을 했다.'],
  ['multiple', '다수의', 'There were ___ reasons.', '여러 가지 이유가 있었다.'],
  ['single', '단 하나의', 'Not a ___ light was on.', '단 하나의 불도 켜져 있지 않았다.'],
  ['double', '두 배의', 'Order a ___ portion.', '두 배 분량을 주문해라.'],
  ['exact', '정확한', 'Tell me the ___ time.', '정확한 시간을 말해줘.'],
  ['final', '마지막의', 'This is the ___ round.', '이번이 마지막 라운드다.'],
  ['initial', '처음의', 'Our ___ plan failed.', '우리의 처음 계획은 실패했다.'],
  ['original', '원래의', 'The ___ copy is missing.', '원본이 사라졌다.'],
  ['additional', '추가의', 'We need ___ chairs.', '우리는 추가 의자가 필요하다.'],
  ['sufficient', '충분한', 'Bring ___ water.', '충분한 물을 가져와라.'],
  ['adequate', '적당한', 'The lighting is ___ .', '조명이 적당하다.'],
  ['constant', '끊임없는', 'There was ___ noise outside.', '밖에서 끊임없는 소음이 있었다.'],
  ['frequent', '잦은', 'He is a ___ visitor.', '그는 자주 오는 방문객이다.'],
  ['occasional', '가끔의', 'We take ___ breaks.', '우리는 가끔 휴식을 취한다.'],
  ['temporary', '일시적인', 'This is a ___ solution.', '이것은 일시적인 해결책이다.'],
  ['permanent', '영구적인', 'She found a ___ job.', '그녀는 정규직을 구했다.'],
  ['ordinary', '평범한', 'It was an ___ Tuesday.', '그것은 평범한 화요일이었다.'],
  ['unusual', '흔치 않은', 'That is an ___ color.', '그것은 흔치 않은 색이다.'],
  ['familiar', '익숙한', 'The tune sounded ___ .', '그 곡조는 익숙하게 들렸다.'],
  ['foreign', '외국의', 'She studies a ___ language.', '그녀는 외국어를 공부한다.'],
  ['distant', '먼', 'They come from a ___ island.', '그들은 먼 섬에서 왔다.'],
  ['nearby', '가까운', 'Is there a ___ pharmacy?', '가까운 약국이 있나요?'],
  ['central', '중심의', 'The ___ office moved.', '중심 사무소가 이전했다.'],
  ['northern', '북쪽의', 'The ___ region is colder.', '북쪽 지역은 더 춥다.'],
  ['southern', '남쪽의', 'The ___ coast is warmer.', '남쪽 해안은 더 따뜻하다.'],
  ['eastern', '동쪽의', 'The ___ sky brightened.', '동쪽 하늘이 밝아졌다.'],
  ['western', '서쪽의', 'They drove to the ___ border.', '그들은 서쪽 국경으로 차를 몰았다.'],
  ['vegetable', '채소', 'Eat one green ___ each day.', '매일 초록 채소를 하나씩 먹어라.'],
  ['furniture', '가구', 'They bought new ___ for the flat.', '그들은 아파트에 놓을 새 가구를 샀다.'],
  ['calculate', '계산하다', 'Please ___ the total cost.', '총 비용을 계산해 주세요.'],
  ['calendar', '달력', 'Mark the date on the ___ .', '달력에 그 날짜를 표시해라.'],
  ['schedule', '일정', 'Check the next day’s ___ carefully.', '내일 일정을 자세히 확인해라.'],
  ['deadline', '마감일', 'The ___ is next Friday.', '마감일은 다음 주 금요일이다.'],
  ['calorie', '칼로리', 'This snack has few ___ s.', '이 간식은 칼로리가 낮다.'],
  ['diagram', '도표', 'The ___ shows the process clearly.', '그 도표는 과정을 명확히 보여 준다.'],
  ['document', '문서', 'Please sign this ___ .', '이 문서에 서명해 주세요.'],
  ['envelope', '봉투', 'She sealed the ___ carefully.', '그녀는 봉투를 조심스럽게 봉했다.'],
  ['folder', '폴더', 'Save the file in this ___ .', '이 폴더에 파일을 저장해라.'],
  ['handbook', '안내서', 'Read the employee ___ first.', '먼저 직원 안내서를 읽어라.'],
  ['headline', '헤드라인', 'The ___ caught everyone’s eye.', '그 헤드라인은 모두의 눈길을 끌었다.'],
  ['keyboard', '자판', 'A key on the ___ was stuck.', '자판의 키 하나가 걸려 있었다.'],
  ['language', '언어', 'She speaks three ___ s fluently.', '그녀는 세 언어를 유창하게 구사한다.'],
  ['magazine', '잡지', 'He reads a ___ every week.', '그는 매주 잡지를 읽는다.'],
  ['notebook', '공책', 'She wrote notes in her ___ .', '그녀는 공책에 필기를 했다.'],
  ['password', '비밀번호', 'He forgot his email ___ .', '그는 이메일 비밀번호를 잊어버렸다.'],
  ['printer', '프린터', 'The office ___ ran out of ink.', '사무실 프린터의 잉크가 다 떨어졌다.'],
  ['timetable', '시간표', 'The train ___ changed today.', '기차 시간표가 오늘 바뀌었다.'],
  ['scissors', '가위', 'Use sharp ___ to cut the fabric.', '날카로운 가위로 천을 잘라라.'],
  ['software', '소프트웨어', 'They updated the ___ overnight.', '그들은 밤사이 소프트웨어를 업데이트했다.'],
  ['sentence', '문장', 'Write a full ___ , please.', '완전한 문장으로 써 주세요.'],
  ['syllable', '음절', 'The word has two ___ s.', '그 단어는 두 음절이다.'],
  ['vocabulary', '어휘', 'Reading builds your ___ .', '독서는 어휘력을 키워 준다.'],
  ['dictionary', '사전', 'Look the word up in a ___ .', '그 단어를 사전에서 찾아봐라.'],
  ['paragraph', '문단', 'Start a new ___ here.', '여기서 새 문단을 시작해라.'],
  ['chapter', '장(챕터)', 'Finish this ___ tonight.', '오늘 밤 이 장을 끝내라.'],
  ['grammar', '문법', 'His ___ improved a lot.', '그의 문법 실력이 많이 향상되었다.'],
  ['spelling', '철자', 'Check the ___ before you submit.', '제출하기 전에 철자를 확인해라.'],
  ['pronounce', '발음하다', 'It is hard to ___ that name.', '그 이름을 발음하기가 어렵다.'],
  ['translate', '번역하다', 'Can you ___ this sentence?', '이 문장을 번역해 줄 수 있니?'],
  ['interpret', '통역하다', 'She will ___ for the guest.', '그녀가 손님을 위해 통역할 것이다.'],
  ['accent', '억양', 'He has a strong regional ___ .', '그는 지역 억양이 강하다.'],
  ['fluent', '유창한', 'She is ___ in Japanese.', '그녀는 일본어가 유창하다.'],
  ['bilingual', '이중 언어의', 'Their kids are ___ .', '그들의 아이들은 두 언어를 구사한다.'],
  ['native', '모국어의', 'English is his ___ language.', '영어는 그의 모국어이다.'],
  ['dialogue', '대화', 'The movie has sharp ___ .', '그 영화는 날카로운 대사가 있다.'],
  ['narrative', '이야기', 'The book has a slow ___ .', '그 책은 이야기 전개가 느리다.'],
  ['fiction', '소설', 'She prefers ___ to nonfiction.', '그녀는 논픽션보다 소설을 좋아한다.'],
  ['biography', '전기(책)', 'He wrote a ___ of the artist.', '그는 그 예술가의 전기를 썼다.'],
  ['heroine', '여주인공', 'The ___ dies at the end.', '여주인공은 결말에서 죽는다.'],
  ['audience', '관객', 'The ___ applauded loudly.', '관객들이 크게 박수쳤다.'],
  ['theater', '극장', 'They watched a play at the ___ .', '그들은 극장에서 연극을 관람했다.'],
  ['orchestra', '오케스트라', 'The ___ played beautifully.', '오케스트라는 아름답게 연주했다.'],
  ['rhythm', '리듬', 'The song has a catchy ___ .', '그 노래는 리듬이 경쾌하다.'],
  ['melody', '멜로디', 'She hummed a cheerful ___ .', '그녀는 경쾌한 멜로디를 흥얼거렸다.'],
  ['harmony', '화음', 'The choir sang in perfect ___ .', '합창단은 완벽한 화음으로 노래했다.'],
  ['instrument', '악기', 'He plays a wind ___ .', '그는 관악기를 연주한다.'],
  ['festival', '축제', 'The town holds a summer ___ .', '그 마을은 여름 축제를 연다.'],
  ['ceremony', '의식', 'The wedding ___ was lovely.', '그 결혼식은 아름다웠다.'],
  ['occasion', '행사', 'It called for a special ___ .', '그것은 특별한 행사를 요했다.'],
  ['holiday', '휴일', 'We plan a trip for the ___ .', '우리는 휴일에 여행을 계획한다.'],
  ['vacation', '휴가', 'They spent their ___ at the beach.', '그들은 해변에서 휴가를 보냈다.'],
  ['journey', '여정', 'The ___ took three days.', '그 여정은 사흘이 걸렸다.'],
  ['destination', '목적지', 'Paris was their final ___ .', '파리가 그들의 최종 목적지였다.'],
  ['passenger', '승객', 'The bus carried forty ___ s.', '그 버스는 승객 마흔 명을 태웠다.'],
  ['luggage', '수하물', 'She checked her ___ at the counter.', '그녀는 카운터에서 수하물을 부쳤다.'],
  ['airport', '공항', 'We arrived at the ___ early.', '우리는 공항에 일찍 도착했다.'],
  ['airline', '항공사', 'The ___ delayed the flight.', '그 항공사는 비행편을 지연시켰다.'],
  ['customs', '세관', 'They waited in line at ___ .', '그들은 세관에서 줄을 서서 기다렸다.'],
  ['passport', '여권', 'Do not forget your ___ .', '여권을 잊지 마라.'],
  ['visa', '비자', 'Her ___ expired last month.', '그녀의 비자는 지난달 만료되었다.'],
  ['embassy', '대사관', 'He visited the ___ for a stamp.', '그는 도장을 받으러 대사관에 갔다.'],
  ['citizen', '시민', 'Every ___ has the right to vote.', '모든 시민은 투표할 권리가 있다.'],
  ['immigrant', '이민자', 'The ___ started a small shop.', '그 이민자는 작은 가게를 열었다.'],
  ['refugee', '난민', 'The camp housed many ___ s.', '그 캠프에는 많은 난민이 거주했다.'],
  ['diplomat', '외교관', 'The ___ met with local leaders.', '그 외교관은 지역 지도자들을 만났다.'],
  ['treaty', '조약', 'Both nations signed the ___ .', '양국은 그 조약에 서명했다.'],
  ['alliance', '동맹', 'The two countries formed an ___ .', '두 나라는 동맹을 맺었다.'],
  ['conflict', '갈등', 'The ___ lasted for years.', '그 갈등은 수년간 지속되었다.'],
  ['violence', '폭력', 'The film shows too much ___ .', '그 영화는 폭력을 지나치게 보여 준다.'],
  ['weapon', '무기', 'The museum displays old ___ s.', '그 박물관은 오래된 무기를 전시한다.'],
  ['soldier', '군인', 'The ___ returned home safely.', '그 군인은 무사히 귀환했다.'],
  ['commander', '지휘관', 'The ___ led the troops bravely.', '그 지휘관은 군대를 용감하게 이끌었다.'],
  ['captain', '선장/대위', 'The ___ steered the ship carefully.', '선장은 배를 조심스럽게 조종했다.'],
  ['officer', '장교/경관', 'A police ___ stopped the car.', '경찰관이 그 차를 세웠다.'],
  ['prisoner', '죄수', 'The ___ was released early.', '그 죄수는 일찍 석방되었다.'],
  ['penalty', '형벌', 'The judge gave a harsh ___ .', '판사는 가혹한 형을 선고했다.'],
  ['verdict', '평결', 'The jury announced its ___ .', '배심원단이 평결을 발표했다.'],
  ['witness', '목격자', 'The ___ described the accident.', '목격자는 그 사고를 묘사했다.'],
  ['clue', '단서', 'They found a new ___ at the scene.', '그들은 현장에서 새로운 단서를 발견했다.'],
  ['suspect', '용의자', 'Police arrested the main ___ .', '경찰이 주요 용의자를 체포했다.'],
  ['criminal', '범죄자', 'The ___ was caught quickly.', '그 범죄자는 빠르게 붙잡혔다.'],
  ['justice', '정의', 'She fought for ___ all her life.', '그녀는 평생 정의를 위해 싸웠다.'],
  ['freedom', '자유', 'They cherished their new ___ .', '그들은 새로운 자유를 소중히 여겼다.'],
  ['equality', '평등', 'The law promotes ___ .', '그 법은 평등을 증진한다.'],
  ['democracy', '민주주의', '___ depends on active citizens.', '민주주의는 적극적인 시민에 달려 있다.'],
  ['president', '대통령', 'The ___ gave a speech tonight.', '대통령이 오늘 밤 연설했다.'],
  ['minister', '장관', 'The finance ___ resigned.', '재무장관이 사임했다.'],
  ['governor', '주지사', 'The ___ visited the flooded town.', '주지사가 침수된 마을을 방문했다.'],
  ['mayor', '시장(직위)', 'The new ___ promised reform.', '새 시장은 개혁을 약속했다.'],
  ['council', '의회', 'The city ___ met on Monday.', '시의회는 월요일에 모였다.'],
  ['committee', '위원회', 'A small ___ reviewed the plan.', '작은 위원회가 그 계획을 검토했다.'],
  ['budget', '예산', 'The school cut its ___ this year.', '그 학교는 올해 예산을 삭감했다.'],
  ['taxes', '세금', 'They must pay their ___ by May.', '그들은 오월까지 세금을 내야 한다.'],
  ['income', '소득', 'Her ___ increased steadily.', '그녀의 소득은 꾸준히 늘었다.'],
  ['salary', '급여', 'His ___ was raised last year.', '그의 급여는 작년에 인상되었다.'],
  ['wage', '임금', 'The minimum ___ went up.', '최저 임금이 인상되었다.'],
  ['pension', '연금', 'She receives a small ___ .', '그녀는 소액의 연금을 받는다.'],
  ['savings', '저축', 'He kept his ___ in the bank.', '그는 저축을 은행에 맡겼다.'],
  ['debt', '빚', 'They finally paid off their ___ .', '그들은 마침내 빚을 다 갚았다.'],
  ['loan', '대출', 'The bank approved his ___ .', '은행이 그의 대출을 승인했다.'],
  ['interest', '이자', 'The ___ rate rose sharply.', '이자율이 급격히 올랐다.'],
  ['insurance', '보험', 'She bought health ___ .', '그녀는 건강 보험에 가입했다.'],
  ['stock', '주식', 'He invested in tech ___ s.', '그는 기술주에 투자했다.'],
  ['currency', '통화', 'They exchanged local ___ .', '그들은 현지 통화로 환전했다.'],
  ['export', '수출하다', 'The country ___ s a lot of coffee.', '그 나라는 커피를 많이 수출한다.'],
  ['import', '수입하다', 'They ___ most of their oil.', '그들은 석유 대부분을 수입한다.'],
  ['factory', '공장', 'The ___ runs day and night.', '그 공장은 밤낮으로 가동된다.'],
  ['warehouse', '창고', 'Boxes filled the huge ___ .', '상자들이 커다란 창고를 채웠다.'],
  ['inventory', '재고', 'They checked the store ___ .', '그들은 매장 재고를 확인했다.'],
  ['shipment', '배송', 'The ___ arrived a day late.', '그 배송은 하루 늦게 도착했다.'],
  ['delivery', '배달', 'The pizza ___ took an hour.', '피자 배달은 한 시간 걸렸다.'],
  ['package', '소포', 'A ___ arrived at the door.', '문 앞에 소포가 도착했다.'],
  ['address', '주소', 'Write your full ___ here.', '여기에 전체 주소를 써라.'],
  ['neighbor', '이웃', 'Our ___ waters our plants.', '우리 이웃이 우리 식물에 물을 준다.'],
  ['resident', '거주자', 'Every ___ received a notice.', '모든 거주자가 통지를 받았다.'],
  ['apartment', '아파트', 'They rent a small ___ .', '그들은 작은 아파트를 임대한다.'],
  ['balcony', '발코니', 'She grows herbs on the ___ .', '그녀는 발코니에서 허브를 기른다.'],
  ['elevator', '엘리베이터', 'The ___ broke down again.', '엘리베이터가 또 고장 났다.'],
  ['basement', '지하실', 'They store tools in the ___ .', '그들은 지하실에 도구를 보관한다.'],
  ['ceiling', '천장', 'A crack appeared on the ___ .', '천장에 금이 갔다.'],
  ['carpet', '카펫', 'They laid a soft ___ down.', '그들은 부드러운 카펫을 깔았다.'],
  ['curtain', '커튼', 'She drew the ___ shut.', '그녀는 커튼을 닫았다.'],
  ['drawer', '서랍', 'He opened the top ___ .', '그는 맨 위 서랍을 열었다.'],
  ['cabinet', '캐비닛', 'Plates are kept in the ___ .', '접시들은 캐비닛에 보관되어 있다.'],
  ['closet', '벽장', 'She hung her coat in the ___ .', '그녀는 벽장에 코트를 걸었다.'],
  ['fireplace', '벽난로', 'They sat near the warm ___ .', '그들은 따뜻한 벽난로 곁에 앉았다.'],
  ['chimney', '굴뚝', 'Smoke rose from the ___ .', '연기가 굴뚝에서 피어올랐다.'],
  ['attic', '다락', 'Old boxes filled the ___ .', '낡은 상자들이 다락을 채웠다.'],
  ['porch', '현관', 'They relaxed on the front ___ .', '그들은 현관에서 쉬었다.'],
  ['driveway', '진입로', 'The car was parked in the ___ .', '차는 진입로에 주차되어 있었다.'],
  ['sidewalk', '보도', 'Children played on the ___ .', '아이들이 보도에서 놀았다.'],
  ['pavement', '포장도로', 'Rain made the ___ slippery.', '비가 와서 포장도로가 미끄러웠다.'],
  ['highway', '고속도로', 'Traffic on the ___ was heavy.', '고속도로 교통량이 많았다.'],
  ['tunnel', '터널', 'The car sped through the ___ .', '자동차는 터널을 빠르게 지나갔다.'],
  ['crossing', '건널목', 'Wait at the ___ for the light.', '건널목에서 신호를 기다려라.'],
  ['pedestrian', '보행자', 'The ___ crossed carefully.', '그 보행자는 조심스럽게 건넜다.'],
  ['vehicle', '차량', 'That ___ needs new tires.', '그 차량은 새 타이어가 필요하다.'],
  ['traffic', '교통', 'Heavy ___ delayed the bus.', '심한 교통 체증이 버스를 지연시켰다.'],
  ['license', '면허', 'He renewed his driving ___ .', '그는 운전면허를 갱신했다.'],
  ['mechanic', '정비공', 'The ___ fixed the flat tire.', '그 정비공은 펑크 난 타이어를 고쳤다.'],
  ['gasoline', '휘발유', 'The car ran out of ___ .', '차에 휘발유가 떨어졌다.'],
  ['pollution', '오염', 'Air ___ worsened this week.', '이번 주 대기 오염이 심해졌다.'],
  ['climate', '기후', 'The ___ here is mild.', '이곳의 기후는 온화하다.'],
  ['drought', '가뭄', 'The region suffered a long ___ .', '그 지역은 긴 가뭄을 겪었다.'],
  ['flood', '홍수', 'A sudden ___ damaged homes.', '갑작스러운 홍수가 집들을 훼손했다.'],
  ['earthquake', '지진', 'The ___ shook the whole city.', '그 지진은 도시 전체를 뒤흔들었다.'],
  ['volcano', '화산', 'The ___ erupted after decades.', '그 화산은 수십 년 만에 폭발했다.'],
  ['tornado', '토네이도', 'A ___ tore through the fields.', '토네이도가 들판을 휩쓸었다.'],
  ['hurricane', '허리케인', 'The ___ hit the coast hard.', '허리케인이 해안을 강타했다.'],
  ['wildlife', '야생 생물', 'The park protects local ___ .', '그 공원은 지역 야생 생물을 보호한다.'],
  ['species', '종(생물)', 'A rare ___ was discovered.', '희귀종이 발견되었다.'],
  ['habitat', '서식지', 'Deforestation destroys their ___ .', '벌목은 그들의 서식지를 파괴한다.'],
  ['predator', '포식자', 'The eagle is a skilled ___ .', '독수리는 노련한 포식자이다.'],
  ['creature', '생물', 'A strange ___ hid in the cave.', '이상한 생물이 동굴에 숨어 있었다.'],
  ['reptile', '파충류', 'A snake is a kind of ___ .', '뱀은 파충류의 일종이다.'],
  ['mammal', '포유류', 'A whale is a marine ___ .', '고래는 해양 포유류이다.'],
  ['pollinate', '수분하다', 'Bees help ___ the flowers.', '벌은 꽃가루받이를 돕는다.'],
  ['harvest', '수확하다', 'Farmers ___ wheat in autumn.', '농부들은 가을에 밀을 수확한다.'],
  ['fertilize', '비옥하게 하다', 'They ___ the soil each spring.', '그들은 매년 봄 땅을 비옥하게 한다.'],
  ['irrigate', '관개하다', 'Farmers ___ the dry fields.', '농부들은 마른 밭에 물을 댄다.'],
  ['livestock', '가축', 'The farm raises ___ for milk.', '그 농장은 우유를 위해 가축을 키운다.'],
  ['pasture', '목초지', 'Cattle graze in the ___ .', '소들이 목초지에서 풀을 뜯는다.'],
  ['orchard', '과수원', 'They picked apples in the ___ .', '그들은 과수원에서 사과를 땄다.'],
  ['seedling', '묘목', 'She planted a young ___ .', '그녀는 어린 묘목을 심었다.'],
  ['blossom', '꽃', 'Cherry ___ s fill the park.', '벚꽃이 공원을 가득 채운다.'],
  ['petal', '꽃잎', 'A pink ___ fell to the ground.', '분홍 꽃잎이 땅에 떨어졌다.'],
  ['stem', '줄기', 'The flower has a thin ___ .', '그 꽃은 가느다란 줄기를 가지고 있다.'],
  ['root', '뿌리', 'Deep ___ s hold the tree steady.', '깊은 뿌리가 나무를 단단히 지탱한다.'],
  ['branch', '나뭇가지', 'A bird sat on the ___ .', '새 한 마리가 나뭇가지에 앉았다.'],
  ['trunk', '나무 몸통', 'The old tree ___ was hollow.', '그 오래된 나무 몸통은 속이 비어 있었다.'],
  ['satellite', '위성', 'The ___ orbits the earth.', '그 위성은 지구 궤도를 돈다.'],
  ['telescope', '망원경', 'She viewed Mars through a ___ .', '그녀는 망원경으로 화성을 관측했다.'],
  ['microscope', '현미경', 'Cells are visible under a ___ .', '세포는 현미경으로 볼 수 있다.'],
  ['chemical', '화학의', 'The lab handles ___ waste carefully.', '그 실험실은 화학 폐기물을 조심스럽게 다룬다.'],
  ['molecule', '분자', 'Water is made of a simple ___ .', '물은 단순한 분자로 이루어져 있다.'],
  ['particle', '입자', 'A dust ___ floated by.', '먼지 입자 하나가 떠다녔다.'],
  ['gravity', '중력', '___ pulls objects downward.', '중력은 물체를 아래로 끌어당긴다.'],
  ['universe', '우주', 'The ___ keeps expanding.', '우주는 계속 팽창한다.'],
  ['galaxy', '은하', 'Our ___ has billions of stars.', '우리 은하에는 수십억 개의 별이 있다.'],
  ['asteroid', '소행성', 'An ___ passed near Earth.', '소행성 하나가 지구 근처를 지나갔다.'],
  ['comet', '혜성', 'The ___ appears every century.', '그 혜성은 백 년마다 나타난다.'],
  ['orbit', '궤도', 'The moon stays in ___ around Earth.', '달은 지구 주위 궤도에 머무른다.'],
  ['surgeon', '외과의', 'The ___ performed a long operation.', '그 외과의는 긴 수술을 집도했다.'],
  ['patient', '환자', 'The ___ recovered quickly.', '그 환자는 빠르게 회복했다.'],
  ['hospital', '병원', 'She was rushed to the ___ .', '그녀는 병원으로 급히 옮겨졌다.'],
  ['clinic', '진료소', 'The local ___ opens at eight.', '동네 진료소는 여덟 시에 문을 연다.'],
  ['medicine', '약', 'Take this ___ twice a day.', '이 약을 하루에 두 번 복용해라.'],
  ['illness', '질병', 'He recovered from a serious ___ .', '그는 심각한 질병에서 회복했다.'],
  ['symptom', '증상', 'Fever is a common ___ .', '발열은 흔한 증상이다.'],
  ['diagnosis', '진단', 'The doctor gave a clear ___ .', '의사는 명확한 진단을 내렸다.'],
  ['treatment', '치료', 'The ___ took several weeks.', '그 치료는 몇 주가 걸렸다.'],
  ['vaccine', '백신', 'The ___ prevents the flu.', '그 백신은 독감을 예방한다.'],
  ['infection', '감염', 'She caught a minor ___ .', '그녀는 가벼운 감염에 걸렸다.'],
  ['allergy', '알레르기', 'He has a peanut ___ .', '그는 땅콩 알레르기가 있다.'],
  ['exercise', '운동', 'Daily ___ keeps you fit.', '매일 운동하면 건강을 유지할 수 있다.'],
  ['nutrition', '영양', 'Good ___ supports growth.', '좋은 영양은 성장을 돕는다.'],
  ['digestion', '소화', 'Slow eating helps ___ .', '천천히 먹으면 소화에 도움이 된다.'],
  ['appetite', '식욕', 'He lost his ___ after the news.', '그는 그 소식을 듣고 식욕을 잃었다.'],
  ['fatigue', '피로', 'The workers felt deep ___ .', '노동자들은 심한 피로를 느꼈다.'],
]

/* ------------------------------------------------------------------
   상급 — 10글자 이상. 시험이나 글에서 만나는 긴 말들.
   ------------------------------------------------------------------ */
const hard = [
  ['responsibility', '책임', 'Taking ___ is part of growing up.', '책임을 지는 것은 성장의 일부이다.'],
  ['extraordinary', '비범한', 'She showed ___ courage.', '그녀는 비범한 용기를 보여 주었다.'],
  ['international', '국제의', 'They signed an ___ treaty.', '그들은 국제 조약에 서명했다.'],
  ['understanding', '이해', 'We reached a mutual ___ .', '우리는 상호 이해에 도달했다.'],
  ['consideration', '고려', 'Please give it careful ___ .', '그것을 신중히 고려해 주세요.'],
  ['recommendation', '추천', 'His ___ helped me greatly.', '그의 추천이 나에게 큰 도움이 되었다.'],
  ['characteristic', '특징', 'Patience is her main ___ .', '인내심이 그녀의 주된 특징이다.'],
  ['representative', '대표', 'A union ___ spoke first.', '노조 대표가 먼저 발언했다.'],
  ['administration', '행정', 'The new ___ took office.', '새 행정부가 취임했다.'],
  ['communication', '의사소통', 'Clear ___ prevents mistakes.', '명확한 의사소통은 실수를 막는다.'],
  ['determination', '결단력', 'Her ___ impressed everyone.', '그녀의 결단력은 모두를 감동시켰다.'],
  ['investigation', '조사', 'The ___ lasted six months.', '그 조사는 여섯 달 동안 계속되었다.'],
  ['organization', '조직', 'The ___ helps refugees.', '그 조직은 난민들을 돕는다.'],
  ['performance', '성과', 'His ___ improved steadily.', '그의 성과는 꾸준히 향상되었다.'],
  ['relationship', '관계', 'Their ___ grew stronger.', '그들의 관계는 더욱 돈독해졌다.'],
  ['significant', '중대한', 'That was a ___ discovery.', '그것은 중대한 발견이었다.'],
  ['sustainable', '지속 가능한', 'We need ___ energy sources.', '우리는 지속 가능한 에너지원이 필요하다.'],
  ['sophisticated', '정교한', 'The device is highly ___ .', '그 장치는 매우 정교하다.'],
  ['comprehensive', '포괄적인', 'They wrote a ___ report.', '그들은 포괄적인 보고서를 작성했다.'],
  ['controversial', '논란이 많은', 'The decision was ___ .', '그 결정은 논란이 많았다.'],
  ['demonstration', '시연', 'The ___ drew a large crowd.', '그 시연은 많은 관중을 끌어모았다.'],
  ['environmental', '환경의', 'They study ___ damage.', '그들은 환경 피해를 연구한다.'],
  ['fundamental', '근본적인', 'This is a ___ principle.', '이것은 근본적인 원칙이다.'],
  ['independence', '독립', 'The colony gained ___ .', '그 식민지는 독립을 얻었다.'],
  ['intelligence', '지능', 'Artificial ___ is advancing.', '인공 지능이 발전하고 있다.'],
  ['nevertheless', '그럼에도', 'It rained; ___ , we went.', '비가 왔지만, 그럼에도 우리는 갔다.'],
  ['overwhelming', '압도적인', 'The response was ___ .', '그 반응은 압도적이었다.'],
  ['participation', '참여', 'Student ___ was high.', '학생 참여율이 높았다.'],
  ['philosophical', '철학적인', 'He raised a ___ question.', '그는 철학적인 질문을 던졌다.'],
  ['preliminary', '예비의', 'These are ___ results.', '이것은 예비 결과이다.'],
  ['psychological', '심리적인', 'The strain was ___ .', '그 부담은 심리적인 것이었다.'],
  ['qualification', '자격', 'She has every ___ needed.', '그녀는 필요한 모든 자격을 갖췄다.'],
  ['recognition', '인정', 'His work finally gained ___ .', '그의 작품이 마침내 인정을 받았다.'],
  ['remarkable', '놀라운', 'It was a ___ recovery.', '그것은 놀라운 회복이었다.'],
  ['revolutionary', '혁명적인', 'The idea was ___ .', '그 발상은 혁명적이었다.'],
  ['spectacular', '장관인', 'The view was ___ .', '그 경치는 장관이었다.'],
  ['technological', '기술의', '___ progress never stops.', '기술의 발전은 멈추지 않는다.'],
  ['transformation', '변화', 'The ___ took a decade.', '그 변화는 십 년이 걸렸다.'],
  ['unfortunately', '불행히도', '___ , the flight was canceled.', '불행히도 그 항공편은 취소되었다.'],
  ['accommodation', '숙박 시설', 'The ___ was clean and quiet.', '그 숙박 시설은 깨끗하고 조용했다.'],
  ['accomplishment', '업적', 'That was a real ___ .', '그것은 진정한 업적이었다.'],
  ['advertisement', '광고', 'The ___ ran for a month.', '그 광고는 한 달 동안 나갔다.'],
  ['appreciation', '감사', 'She expressed deep ___ .', '그녀는 깊은 감사를 표했다.'],
  ['architecture', '건축', 'Roman ___ still stands.', '로마 건축물은 여전히 남아 있다.'],
  ['circumstance', '상황', 'Under no ___ should you enter.', '어떤 상황에서도 들어가서는 안 된다.'],
  ['collaboration', '협력', 'The ___ produced great work.', '그 협력은 훌륭한 결과물을 만들어 냈다.'],
  ['competition', '경쟁', 'The ___ was fierce.', '그 경쟁은 치열했다.'],
  ['concentration', '집중', 'The task requires ___ .', '그 일은 집중을 요한다.'],
  ['consequence', '결과', 'He faced the ___ calmly.', '그는 그 결과를 침착하게 받아들였다.'],
  ['constitution', '헌법', 'The ___ protects free speech.', '헌법은 언론의 자유를 보호한다.'],
  ['contribution', '기여', 'Her ___ was invaluable.', '그녀의 기여는 매우 소중했다.'],
  ['cooperation', '협조', 'Thank you for your ___ .', '협조해 주셔서 감사합니다.'],
  ['corporation', '기업', 'A large ___ bought the land.', '한 대기업이 그 땅을 매입했다.'],
  ['correspondence', '서신', 'Their ___ lasted years.', '그들의 서신 왕래는 수년간 이어졌다.'],
  ['disappointed', '실망한', 'She looked deeply ___ .', '그녀는 몹시 실망한 표정이었다.'],
  ['discrimination', '차별', 'The law bans ___ .', '그 법은 차별을 금지한다.'],
  ['distribution', '분배', 'The ___ was uneven.', '그 분배는 고르지 못했다.'],
  ['documentation', '문서', 'Bring all the ___ .', '모든 문서를 가져와라.'],
  ['effectiveness', '효과', 'They measured its ___ .', '그들은 그것의 효과를 측정했다.'],
  ['encouragement', '격려', 'Her ___ kept me going.', '그녀의 격려 덕분에 나는 계속할 수 있었다.'],
  ['entertainment', '오락', 'The ___ lasted all evening.', '그 오락 프로그램은 저녁 내내 계속되었다.'],
  ['enthusiasm', '열정', 'He spoke with ___ .', '그는 열정을 담아 말했다.'],
  ['environment', '환경', 'We must protect the ___ .', '우리는 환경을 보호해야 한다.'],
  ['establishment', '설립', 'The ___ of the fund took years.', '그 기금의 설립에는 수년이 걸렸다.'],
  ['examination', '시험', 'The ___ begins at nine.', '시험은 아홉 시에 시작한다.'],
  ['expectation', '기대', 'The result exceeded every ___ .', '그 결과는 모든 기대를 뛰어넘었다.'],
  ['explanation', '설명', 'His ___ made sense.', '그의 설명은 이치에 맞았다.'],
  ['exploration', '탐험', 'Space ___ continues.', '우주 탐험은 계속된다.'],
  ['imagination', '상상력', 'Children have vivid ___ .', '아이들은 생생한 상상력을 가지고 있다.'],
  ['implementation', '시행', 'The ___ starts in May.', '그 시행은 오월에 시작된다.'],
  ['improvement', '개선', 'There is room for ___ .', '개선의 여지가 있다.'],
  ['independent', '독립적인', 'She became financially ___ .', '그녀는 경제적으로 독립적이게 되었다.'],
  ['individual', '개인', 'Each ___ has a role.', '각 개인은 저마다의 역할이 있다.'],
  ['industrial', '산업의', 'The ___ zone expanded.', '산업 단지가 확장되었다.'],
  ['infrastructure', '기반 시설', 'The ___ needs investment.', '그 기반 시설에는 투자가 필요하다.'],
  ['initiative', '주도권', 'He took the ___ himself.', '그는 스스로 주도권을 잡았다.'],
  ['innovation', '혁신', '___ drives their success.', '혁신이 그들의 성공을 이끈다.'],
  ['inspiration', '영감', 'Nature was her ___ .', '자연이 그녀의 영감이었다.'],
  ['institution', '기관', 'The ___ was founded in 1890.', '그 기관은 1890년에 설립되었다.'],
  ['interaction', '상호작용', 'Social ___ matters to children.', '사회적 상호작용은 아이들에게 중요하다.'],
  ['interpretation', '해석', 'Her ___ differed from mine.', '그녀의 해석은 나의 것과 달랐다.'],
  ['introduction', '소개', 'The ___ was rather long.', '그 소개는 다소 길었다.'],
  ['investment', '투자', 'The ___ paid off well.', '그 투자는 큰 수익을 냈다.'],
  ['legislation', '법률', 'New ___ passed last month.', '새 법률이 지난달 통과되었다.'],
  ['maintenance', '유지 보수', 'Regular ___ prevents damage.', '정기적인 유지 보수는 손상을 막는다.'],
  ['manufacture', '제조하다', 'They ___ medical devices.', '그들은 의료 기기를 제조한다.'],
  ['negotiation', '협상', 'The ___ lasted all night.', '그 협상은 밤새 계속되었다.'],
  ['observation', '관찰', 'That is a sharp ___ .', '그것은 예리한 관찰이다.'],
  ['occupation', '직업', 'State your ___ here.', '여기에 직업을 적으세요.'],
  ['perspective', '관점', 'Try another ___ .', '다른 관점에서 시도해 봐라.'],
  ['possibility', '가능성', 'There is a slight ___ .', '약간의 가능성이 있다.'],
  ['preparation', '준비', 'The ___ took weeks.', '그 준비에는 몇 주가 걸렸다.'],
  ['presentation', '발표', 'Her ___ was clear.', '그녀의 발표는 명료했다.'],
  ['production', '생산', 'Steel ___ increased.', '철강 생산이 증가했다.'],
  ['profession', '직업', 'Teaching is a noble ___ .', '교직은 고귀한 직업이다.'],
  ['protection', '보호', 'Wear gloves for ___ .', '보호를 위해 장갑을 껴라.'],
  ['publication', '출판', 'The ___ date moved.', '출판일이 변경되었다.'],
  ['reflection', '반영', 'Sales are a ___ of quality.', '매출은 품질의 반영이다.'],
  ['regulation', '규정', 'Every ___ must be followed.', '모든 규정은 준수되어야 한다.'],
  ['reputation', '평판', 'The shop has a good ___ .', '그 가게는 평판이 좋다.'],
  ['resistance', '저항', 'They met strong ___ .', '그들은 강한 저항에 부딪혔다.'],
  ['resolution', '결의', 'The council passed a ___ .', '의회는 결의안을 통과시켰다.'],
  ['satisfaction', '만족', 'She smiled with ___ .', '그녀는 만족한 듯 미소 지었다.'],
  ['significance', '중요성', 'Few grasped its ___ .', '그 중요성을 이해한 사람은 거의 없었다.'],
  ['specialist', '전문가', 'Ask a ___ about it.', '그것에 대해 전문가에게 물어봐라.'],
  ['statistics', '통계', 'The ___ tell a clear story.', '그 통계는 명확한 이야기를 들려준다.'],
  ['supervision', '감독', 'Work under close ___ .', '철저한 감독 아래 작업해라.'],
  ['technology', '기술', 'Modern ___ changed everything.', '현대 기술은 모든 것을 바꿔 놓았다.'],
  ['temperature', '온도', 'The ___ dropped sharply.', '온도가 급격히 떨어졌다.'],
  ['university', '대학교', 'He entered ___ last year.', '그는 작년에 대학교에 입학했다.'],
  ['acknowledge', '인정하다', 'Please ___ receipt of this.', '이것의 수령을 확인해 주세요.'],
  ['accumulate', '축적하다', 'Dust tends to ___ here.', '먼지가 여기에 잘 쌓이는 편이다.'],
  ['anticipate', '예상하다', 'We ___ heavy traffic.', '우리는 심한 교통 체증을 예상한다.'],
  ['appreciate', '감사하다', 'I truly ___ your help.', '나는 당신의 도움에 진심으로 감사한다.'],
  ['approximately', '대략', 'It costs ___ fifty dollars.', '그것은 대략 오십 달러가 든다.'],
  ['assumption', '가정', 'That ___ proved wrong.', '그 가정은 틀린 것으로 밝혀졌다.'],
  ['collaborate', '협력하다', 'The two teams will ___ .', '두 팀이 협력할 것이다.'],
  ['commitment', '헌신', 'Her ___ never wavered.', '그녀의 헌신은 결코 흔들리지 않았다.'],
  ['compensate', '보상하다', 'They will ___ the loss.', '그들은 손실을 보상할 것이다.'],
  ['competitive', '경쟁적인', 'The market is very ___ .', '그 시장은 경쟁이 매우 치열하다.'],
  ['comprehend', '이해하다', 'It is hard to ___ the scale.', '그 규모를 이해하기는 어렵다.'],
  ['concentrate', '집중하다', 'Please ___ on the task.', '그 일에 집중해 주세요.'],
  ['confidence', '자신감', 'She spoke with ___ .', '그녀는 자신감 있게 말했다.'],
  ['confirmation', '확인', 'We await written ___ .', '우리는 서면 확인을 기다린다.'],
  ['consequently', '결과적으로', 'It rained; ___ , we stayed.', '비가 왔고, 결과적으로 우리는 남았다.'],
  ['considerable', '상당한', 'It required ___ effort.', '그것은 상당한 노력을 필요로 했다.'],
  ['consistent', '일관된', 'His results are ___ .', '그의 결과는 일관되다.'],
  ['constructive', '건설적인', 'She gave ___ feedback.', '그녀는 건설적인 피드백을 주었다.'],
  ['contemporary', '현대의', 'This is ___ music.', '이것은 현대 음악이다.'],
  ['controversy', '논란', 'The film caused ___ .', '그 영화는 논란을 일으켰다.'],
  ['conventional', '관습적인', 'They chose a ___ approach.', '그들은 관습적인 방식을 택했다.'],
  ['convincing', '설득력 있는', 'His argument was ___ .', '그의 주장은 설득력이 있었다.'],
  ['coordination', '조정', 'The task needs ___ .', '그 작업에는 조정이 필요하다.'],
  ['definitely', '분명히', 'I will ___ attend.', '나는 분명히 참석할 것이다.'],
  ['dependence', '의존', 'Reduce your ___ on cars.', '자동차에 대한 의존을 줄여라.'],
  ['desperately', '필사적으로', 'He searched ___ .', '그는 필사적으로 찾았다.'],
  ['distinguish', '구별하다', 'Can you ___ the two sounds?', '그 두 소리를 구별할 수 있니?'],
  ['distinctive', '독특한', 'It has a ___ flavor.', '그것은 독특한 맛을 가지고 있다.'],
  ['dramatically', '극적으로', 'Costs rose ___ .', '비용이 극적으로 올랐다.'],
  ['accessibility', '접근성', 'They improved website ___ .', '그들은 웹사이트 접근성을 개선했다.'],
  ['accountability', '책임', 'Voters demanded ___ .', '유권자들은 책임을 요구했다.'],
  ['essentially', '본질적으로', 'They are ___ the same.', '그것들은 본질적으로 같다.'],
  ['achievement', '성취', 'Winning was a huge ___ .', '우승은 커다란 성취였다.'],
  ['eventually', '결국', 'She ___ agreed.', '그녀는 결국 동의했다.'],
  ['exaggerate', '과장하다', 'Do not ___ the danger.', '위험을 과장하지 마라.'],
  ['exceptional', '뛰어난', 'The service was ___ .', '그 서비스는 뛰어났다.'],
  ['expenditure', '지출', 'Cut unnecessary ___ .', '불필요한 지출을 줄여라.'],
  ['experiment', '실험', 'The ___ succeeded.', '그 실험은 성공했다.'],
  ['fascinating', '매혹적인', 'The lecture was ___ .', '그 강연은 매혹적이었다.'],
  ['frequently', '자주', 'He travels ___ .', '그는 자주 여행한다.'],
  ['generation', '세대', 'Each ___ faces new problems.', '각 세대는 새로운 문제에 직면한다.'],
  ['advancement', '발전', 'Medical ___ saves lives.', '의학의 발전은 생명을 구한다.'],
  ['illustrate', '설명하다', 'Let me ___ with an example.', '예를 들어 설명해 볼게.'],
  ['immediately', '즉시', 'Call me ___ .', '즉시 나에게 전화해라.'],
  ['impressive', '인상적인', 'The result was ___ .', '그 결과는 인상적이었다.'],
  ['incredible', '믿기 힘든', 'The story sounds ___ .', '그 이야기는 믿기 힘들게 들린다.'],
  ['inevitable', '피할 수 없는', 'Change was ___ .', '변화는 피할 수 없었다.'],
  ['influential', '영향력 있는', 'She is an ___ critic.', '그녀는 영향력 있는 평론가이다.'],
  ['ingredient', '재료', 'Salt is a key ___ .', '소금은 핵심 재료이다.'],
  ['inhabitant', '주민', 'Every ___ was evacuated.', '모든 주민이 대피했다.'],
  ['insufficient', '불충분한', 'The funds were ___ .', '자금이 불충분했다.'],
  ['intellectual', '지적인', 'It was an ___ debate.', '그것은 지적인 토론이었다.'],
  ['investigate', '조사하다', 'Police will ___ the case.', '경찰이 그 사건을 조사할 것이다.'],
  ['justification', '정당화', 'There is no ___ for it.', '그것에 대한 정당화는 없다.'],
  ['legitimate', '정당한', 'She raised a ___ concern.', '그녀는 정당한 우려를 제기했다.'],
  ['magnificent', '웅장한', 'The hall was ___ .', '그 홀은 웅장했다.'],
  ['manipulate', '조종하다', 'Do not ___ the data.', '데이터를 조작하지 마라.'],
  ['measurement', '측정', 'Take an exact ___ .', '정확한 측정값을 재라.'],
  ['mysterious', '신비한', 'A ___ light appeared.', '신비한 빛이 나타났다.'],
  ['alternative', '대안', 'Is there a cheaper ___ ?', '더 저렴한 대안이 있나요?'],
  ['nutritious', '영양가 있는', 'Beans are highly ___ .', '콩은 영양가가 매우 높다.'],
  ['obligation', '의무', 'You have no ___ to answer.', '당신은 대답할 의무가 없다.'],
  ['occasionally', '가끔', 'We meet ___ .', '우리는 가끔 만난다.'],
  ['originally', '원래', 'It was ___ a barn.', '그것은 원래 헛간이었다.'],
  ['outstanding', '뛰어난', 'Her essay was ___ .', '그녀의 에세이는 뛰어났다.'],
  ['particularly', '특히', 'It is ___ cold today.', '오늘은 특히 춥다.'],
  ['persuasive', '설득력 있는', 'He gave a ___ speech.', '그는 설득력 있는 연설을 했다.'],
  ['phenomenon', '현상', 'This ___ puzzles scientists.', '이 현상은 과학자들을 당황하게 한다.'],
  ['photograph', '사진', 'She framed the old ___ .', '그녀는 오래된 사진을 액자에 넣었다.'],
  ['population', '인구', 'The ___ doubled in ten years.', '인구가 십 년 만에 두 배가 되었다.'],
  ['practically', '사실상', 'The work is ___ done.', '그 작업은 사실상 끝났다.'],
  ['prediction', '예측', 'His ___ proved accurate.', '그의 예측은 정확한 것으로 드러났다.'],
  ['prescription', '처방전', 'Bring your ___ to the counter.', '처방전을 카운터로 가져오세요.'],
  ['presumably', '아마도', 'He is ___ still asleep.', '그는 아마도 아직 자고 있을 것이다.'],
  ['previously', '이전에', 'We ___ met in Seoul.', '우리는 이전에 서울에서 만났다.'],
  ['prohibited', '금지된', 'Smoking is strictly ___ .', '흡연은 엄격히 금지된다.'],
  ['proportion', '비율', 'A large ___ agreed.', '상당한 비율이 동의했다.'],
  ['reasonable', '합리적인', 'The price seems ___ .', '그 가격은 합리적으로 보인다.'],
  ['reluctantly', '마지못해', 'She ___ accepted.', '그녀는 마지못해 받아들였다.'],
  ['representation', '대표', 'They demanded fair ___ .', '그들은 공정한 대표성을 요구했다.'],
  ['respectively', '각각', 'They finished first and third, ___ .', '그들은 각각 일 등과 삼 등을 했다.'],
  ['restriction', '제한', 'The ___ was lifted.', '그 제한이 해제되었다.'],
  ['simultaneously', '동시에', 'Both alarms rang ___ .', '두 경보가 동시에 울렸다.'],
  ['specifically', '구체적으로', 'He asked ___ about cost.', '그는 비용에 대해 구체적으로 물었다.'],
  ['substantial', '상당한', 'They made a ___ profit.', '그들은 상당한 이익을 냈다.'],
  ['sufficiently', '충분히', 'The soup is ___ warm.', '그 수프는 충분히 따뜻하다.'],
  ['surprisingly', '놀랍게도', '___ , nobody complained.', '놀랍게도 아무도 불평하지 않았다.'],
  ['unexpectedly', '예기치 않게', 'He arrived ___ early.', '그는 예기치 않게 일찍 도착했다.'],
  ['consciousness', '의식', 'He regained ___ after an hour.', '그는 한 시간 후 의식을 되찾았다.'],
  ['contradiction', '모순', 'Her story contained a ___ .', '그녀의 이야기에는 모순이 있었다.'],
  ['unbelievable', '믿기 힘든', 'The comeback was ___ .', '그 역전승은 믿기 힘들었다.'],
  ['unpredictable', '예측 불가능한', 'The weather here is ___ .', '이곳 날씨는 예측 불가능하다.'],
  ['unnecessary', '불필요한', 'Avoid ___ spending this month.', '이번 달에는 불필요한 지출을 피해라.'],
  ['undoubtedly', '의심할 여지 없이', 'She is ___ the best candidate.', '그녀는 의심할 여지 없이 최고의 후보이다.'],
  ['unavoidable', '피할 수 없는', 'The delay was ___ .', '그 지연은 피할 수 없었다.'],
  ['unbearable', '견딜 수 없는', 'The heat became ___ .', '더위가 견딜 수 없게 되었다.'],
  ['unconscious', '무의식의', 'He was found ___ on the floor.', '그는 바닥에 무의식 상태로 발견되었다.'],
  ['underground', '지하의', 'They built an ___ tunnel.', '그들은 지하 터널을 건설했다.'],
  ['underneath', '아래에', 'The cat hid ___ the sofa.', '고양이는 소파 아래에 숨었다.'],
  ['understandable', '이해할 만한', 'His anger was ___ .', '그의 분노는 이해할 만했다.'],
  ['underestimate', '과소평가하다', 'Never ___ your opponent.', '결코 상대를 과소평가하지 마라.'],
  ['overestimate', '과대평가하다', 'They tend to ___ the cost.', '그들은 비용을 과대평가하는 경향이 있다.'],
  ['perseverance', '인내', 'Her ___ finally paid off.', '그녀의 인내가 마침내 결실을 맺었다.'],
  ['overwhelmed', '압도된', 'He felt ___ by the workload.', '그는 업무량에 압도당했다.'],
  ['overweight', '과체중의', 'The vet said the dog was ___ .', '수의사는 그 개가 과체중이라고 말했다.'],
  ['immigration', '이민', 'The country welcomed more ___ .', '그 나라는 더 많은 이민을 받아들였다.'],
  ['globalization', '세계화', '___ connects distant markets.', '세계화는 먼 시장들을 연결한다.'],
  ['nationwide', '전국적인', 'The strike became ___ .', '그 파업은 전국적으로 번졌다.'],
  ['countryside', '시골', 'They moved to the quiet ___ .', '그들은 조용한 시골로 이사했다.'],
  ['neighborhood', '동네', 'The ___ felt safe and friendly.', '그 동네는 안전하고 친근하게 느껴졌다.'],
  ['skyscraper', '고층 건물', 'A new ___ dominates downtown.', '새 고층 건물이 시내를 압도한다.'],
  ['headquarters', '본사', 'The company moved its ___ .', '그 회사는 본사를 이전했다.'],
  ['transportation', '운송', 'They rely on truck ___ .', '그들은 트럭 운송에 의존한다.'],
  ['marketplace', '시장(개념)', 'Competition in the ___ is fierce.', '시장에서의 경쟁은 치열하다.'],
  ['entrepreneur', '기업가', 'The young ___ launched a startup.', '그 젊은 기업가는 스타트업을 창업했다.'],
  ['shareholders', '주주들', 'The ___ approved the merger.', '주주들은 그 합병을 승인했다.'],
  ['stakeholder', '이해관계자', 'Every ___ was consulted.', '모든 이해관계자가 상담을 받았다.'],
  ['negotiator', '협상가', 'She hired a skilled ___ .', '그녀는 노련한 협상가를 고용했다.'],
  ['spokesperson', '대변인', 'The ___ read a brief statement.', '대변인이 짧은 성명을 읽었다.'],
  ['broadcaster', '방송인', 'The ___ covered the election live.', '그 방송인은 선거를 생중계했다.'],
  ['journalist', '기자', 'A ___ interviewed the mayor.', '기자가 시장을 인터뷰했다.'],
  ['photographer', '사진작가', 'The ___ captured the sunset.', '그 사진작가는 노을을 담아냈다.'],
  ['illustrator', '삽화가', 'The book’s ___ won an award.', '그 책의 삽화가는 상을 받았다.'],
  ['choreographer', '안무가', 'The ___ designed the dance.', '그 안무가는 춤을 설계했다.'],
  ['veterinarian', '수의사', 'The ___ treated the injured owl.', '그 수의사는 다친 부엉이를 치료했다.'],
  ['pharmacist', '약사', 'The ___ explained the dosage.', '그 약사는 복용량을 설명했다.'],
  ['accountant', '회계사', 'Her ___ filed the taxes early.', '그녀의 회계사는 세금 신고를 일찍 마쳤다.'],
  ['electrician', '전기 기사', 'The ___ fixed the wiring.', '그 전기 기사는 배선을 고쳤다.'],
  ['contractor', '도급업자', 'The ___ finished the renovation.', '그 도급업자가 리모델링을 끝냈다.'],
  ['blacksmith', '대장장이', 'The ___ forged a new sword.', '그 대장장이가 새 검을 벼려냈다.'],
  ['bibliophile', '애서가', 'The ___ collects rare books.', '그 애서가는 희귀본을 수집한다.'],
  ['archaeologist', '고고학자', 'The ___ uncovered ancient ruins.', '그 고고학자는 고대 유적을 발굴했다.'],
  ['astronomer', '천문학자', 'The ___ discovered a new star.', '그 천문학자는 새로운 별을 발견했다.'],
  ['biochemist', '생화학자', 'The ___ studies enzymes.', '그 생화학자는 효소를 연구한다.'],
  ['seismologist', '지진학자', 'The ___ tracks earthquakes.', '그 지진학자는 지진을 추적한다.'],
  ['statistician', '통계학자', 'The ___ analyzed the data.', '그 통계학자는 데이터를 분석했다.'],
  ['philosopher', '철학자', 'The ___ questioned everything.', '그 철학자는 모든 것에 의문을 제기했다.'],
  ['anthropologist', '인류학자', 'The ___ studied ancient tribes.', '그 인류학자는 고대 부족을 연구했다.'],
  ['astrophysicist', '천체물리학자', 'The ___ explained black holes.', '그 천체물리학자는 블랙홀을 설명했다.'],
  ['firefighter', '소방관', 'The ___ rescued the family.', '그 소방관은 그 가족을 구조했다.'],
  ['coastguard', '해안경비대', 'The ___ rescued the sailors.', '해안경비대가 선원들을 구조했다.'],
  ['babysitter', '베이비시터', 'The ___ read the kids a story.', '베이비시터는 아이들에게 이야기를 읽어 주었다.'],
  ['housekeeper', '가사 도우미', 'The ___ tidied every room.', '그 가사 도우미는 모든 방을 정돈했다.'],
  ['restaurateur', '레스토랑 경영자', 'The ___ opened a new bistro.', '그 레스토랑 경영자는 새 비스트로를 열었다.'],
  ['chambermaid', '객실 청소원', 'The ___ cleaned the room quickly.', '객실 청소원은 방을 빠르게 청소했다.'],
  ['receptionist', '접수원', 'The ___ greeted every visitor.', '접수원은 모든 방문객을 맞이했다.'],
  ['supervisor', '감독관', 'Her ___ praised the report.', '그녀의 감독관은 보고서를 칭찬했다.'],
  ['apprentice', '견습생', 'The ___ learned from the master.', '그 견습생은 장인에게서 배웠다.'],
  ['internship', '인턴십', 'She completed a summer ___ .', '그녀는 여름 인턴십을 마쳤다.'],
  ['graduation', '졸업', 'Her ___ ceremony was emotional.', '그녀의 졸업식은 감동적이었다.'],
  ['scholarship', '장학금', 'He earned a full ___ .', '그는 전액 장학금을 받았다.'],
  ['curriculum', '교육 과정', 'The school updated its ___ .', '그 학교는 교육 과정을 개편했다.'],
  ['assignment', '과제', 'Turn in the ___ by Friday.', '금요일까지 과제를 제출해라.'],
  ['schoolmate', '학교 친구', 'My ___ helped me with math.', '내 학교 친구가 수학을 도와주었다.'],
  ['headmaster', '교장(학교장)', 'The ___ welcomed new students.', '교장 선생님이 신입생들을 환영했다.'],
  ['instructor', '강사', 'The ___ gave a fascinating lecture.', '그 강사는 흥미로운 강의를 했다.'],
  ['coursework', '학업 과제', '___ took most of her time.', '학업 과제가 그녀 시간 대부분을 차지했다.'],
  ['transcript', '성적 증명서', 'He requested his academic ___ .', '그는 자신의 성적 증명서를 요청했다.'],
  ['certificate', '증명서', 'He received a ___ of completion.', '그는 수료 증명서를 받았다.'],
  ['dissertation', '학위 논문', 'She wrote a ___ on ethics.', '그녀는 윤리학에 관한 학위 논문을 썼다.'],
  ['motivation', '동기', 'Praise boosts a child’s ___ .', '칭찬은 아이의 동기를 북돋운다.'],
  ['discipline', '규율', 'The coach demanded strict ___ .', '코치는 엄격한 규율을 요구했다.'],
  ['creativity', '창의성', 'The class encourages ___ .', '그 수업은 창의성을 장려한다.'],
  ['refrigerator', '냉장고(정식)', 'The ___ hummed quietly all night.', '냉장고는 밤새 조용히 웅웅거렸다.'],
  ['thermometer', '온도계', 'The ___ read below zero.', '온도계는 영하를 가리켰다.'],
  ['stethoscope', '청진기', 'The doctor used a ___ .', '의사는 청진기를 사용했다.'],
  ['wheelchair', '휠체어', 'He pushed her ___ up the ramp.', '그는 경사로 위로 그녀의 휠체어를 밀었다.'],
  ['helicopter', '헬리콥터', 'A ___ hovered above the field.', '헬리콥터가 들판 위를 맴돌았다.'],
  ['battleship', '전함', 'The ___ sailed into the harbor.', '전함이 항구로 들어왔다.'],
  ['motorcycle', '오토바이', 'He rides a fast ___ .', '그는 빠른 오토바이를 탄다.'],
  ['locomotive', '기관차', 'The old ___ still runs.', '그 오래된 기관차는 아직도 운행된다.'],
  ['spacecraft', '우주선', 'The ___ landed safely.', '그 우주선은 안전하게 착륙했다.'],
  ['skateboard', '스케이트보드', 'She learned to ride a ___ .', '그녀는 스케이트보드 타는 법을 배웠다.'],
  ['trampoline', '트램펄린', 'The kids jumped on the ___ .', '아이들은 트램펄린 위에서 뛰었다.'],
  ['playground', '놀이터', 'Children ran across the ___ .', '아이들은 놀이터를 가로질러 뛰었다.'],
  ['auditorium', '강당', 'The concert was held in the ___ .', '그 콘서트는 강당에서 열렸다.'],
  ['basketball', '농구', 'They played ___ after school.', '그들은 방과 후 농구를 했다.'],
  ['volleyball', '배구', 'The team practices ___ daily.', '그 팀은 매일 배구를 연습한다.'],
  ['tournament', '토너먼트', 'The ___ lasted a full week.', '그 토너먼트는 일주일 내내 이어졌다.'],
  ['scoreboard', '전광판', 'The ___ showed the final score.', '전광판은 최종 점수를 보여 주었다.'],
  ['spectators', '관중', 'Thousands of ___ filled the stands.', '수천 명의 관중이 관중석을 채웠다.'],
  ['gymnastics', '체조', 'She has practiced ___ for years.', '그녀는 수년간 체조를 연습해 왔다.'],
  ['racecourse', '경주로', 'Horses ran around the ___ .', '말들이 경주로를 돌았다.'],
  ['restaurant', '식당', 'They booked a table at the ___ .', '그들은 그 식당에 자리를 예약했다.'],
  ['reservation', '예약', 'He made a dinner ___ for two.', '그는 두 사람 저녁 예약을 했다.'],
  ['delicatessen', '델리(식품점)', 'They bought cheese at the ___ .', '그들은 그 델리에서 치즈를 샀다.'],
  ['vegetarian', '채식주의자', 'She has been ___ for years.', '그녀는 수년째 채식주의자다.'],
  ['delectable', '아주 맛있는', 'The sauce was rich and ___ .', '그 소스는 진하고 아주 맛있었다.'],
  ['exaggeration', '과장', 'His ___ ruined the story.', '그의 과장이 이야기를 망쳤다.'],
  ['embarrassment', '당황', 'She hid her ___ well.', '그녀는 당황함을 잘 숨겼다.'],
  ['disappointment', '실망', 'He hid his ___ well.', '그는 실망감을 잘 숨겼다.'],
  ['embarrassing', '당황스러운', 'That was an ___ moment.', '그것은 당황스러운 순간이었다.'],
  ['frustration', '좌절감', 'He expressed his ___ loudly.', '그는 좌절감을 크게 표출했다.'],
  ['temptation', '유혹', 'He resisted the ___ .', '그는 유혹을 뿌리쳤다.'],
  ['resignation', '사임', 'The minister’s ___ shocked everyone.', '장관의 사임은 모두를 놀라게 했다.'],
  ['retirement', '은퇴', 'He announced his ___ today.', '그는 오늘 은퇴를 발표했다.'],
  ['celebration', '축하', 'The team held a ___ .', '그 팀은 축하 행사를 열었다.'],
  ['anniversary', '기념일', 'They celebrated their tenth ___ .', '그들은 열 번째 기념일을 축하했다.'],
  ['invitation', '초대장', 'She sent out the wedding ___ .', '그녀는 결혼식 초대장을 보냈다.'],
  ['congratulations', '축하해요', 'He offered his ___ warmly.', '그는 따뜻하게 축하 인사를 건넸다.'],
  ['hospitality', '환대', 'They showed great ___ .', '그들은 큰 환대를 보여 주었다.'],
  ['generosity', '관대함', 'His ___ surprised everyone.', '그의 관대함은 모두를 놀라게 했다.'],
  ['selfishness', '이기심', 'Pure ___ drove his choice.', '순전한 이기심이 그의 선택을 이끌었다.'],
  ['friendliness', '다정함', 'Her ___ put us at ease.', '그녀의 다정함이 우리를 편하게 해 주었다.'],
  ['forgiveness', '용서', 'She asked for his ___ .', '그녀는 그에게 용서를 구했다.'],
  ['compassion', '연민', 'The nurse showed deep ___ .', '그 간호사는 깊은 연민을 보였다.'],
  ['optimistic', '낙관적인', 'She stayed ___ throughout.', '그녀는 내내 낙관적이었다.'],
  ['pessimistic', '비관적인', 'He sounded rather ___ .', '그는 다소 비관적으로 들렸다.'],
  ['enthusiastic', '열정적인', 'The crowd was ___ .', '군중은 열정적이었다.'],
  ['affectionate', '다정한', 'The dog was very ___ .', '그 개는 매우 다정했다.'],
  ['considerate', '사려 깊은', 'He was always ___ of others.', '그는 항상 다른 사람들을 사려 깊게 대했다.'],
  ['thoughtless', '무심한', 'That was a ___ remark.', '그것은 무심한 발언이었다.'],
  ['hardworking', '근면한', 'She is known as ___ .', '그녀는 근면한 사람으로 알려져 있다.'],
  ['determined', '단호한', 'He looked completely ___ .', '그는 완전히 단호해 보였다.'],
  ['persistent', '끈질긴', 'The rain remained ___ .', '비는 끈질기게 계속됐다.'],
  ['cooperative', '협조적인', 'The staff were very ___ .', '직원들은 매우 협조적이었다.'],
  ['imaginative', '상상력이 풍부한', 'The child gave an ___ answer.', '그 아이는 상상력이 풍부한 대답을 했다.'],
  ['resourceful', '수완이 좋은', 'The team was ___ under pressure.', '그 팀은 압박 속에서도 수완이 좋았다.'],
  ['trustworthy', '믿을 만한', 'He is a ___ friend.', '그는 믿을 만한 친구다.'],
  ['respectful', '공손한', 'She spoke in a ___ tone.', '그녀는 공손한 어조로 말했다.'],
  ['disrespect', '무례', 'He showed clear ___ .', '그는 뚜렷한 무례함을 보였다.'],
  ['punctuality', '시간 엄수', 'The company values ___ .', '그 회사는 시간 엄수를 중시한다.'],
  ['flexibility', '유연성', 'Yoga improves ___ .', '요가는 유연성을 향상시킨다.'],
  ['spontaneous', '즉흥적인', 'They took a ___ trip.', '그들은 즉흥적인 여행을 떠났다.'],
  ['suspicious', '의심스러운', 'The package looked ___ .', '그 소포는 의심스러워 보였다.'],
  ['courageous', '용감한', 'She made a ___ decision.', '그녀는 용감한 결정을 내렸다.'],
  ['victorious', '승리한', 'The army returned ___ .', '군대는 승리하여 돌아왔다.'],
  ['triumphant', '의기양양한', 'He wore a ___ smile.', '그는 의기양양한 미소를 지었다.'],
  ['successful', '성공적인', 'The launch was ___ .', '그 발사는 성공적이었다.'],
  ['unsuccessful', '실패한', 'The attempt was ___ .', '그 시도는 실패했다.'],
  ['productive', '생산적인', 'The meeting was very ___ .', '그 회의는 매우 생산적이었다.'],
  ['unproductive', '비생산적인', 'The debate felt ___ .', '그 토론은 비생산적으로 느껴졌다.'],
  ['inexpensive', '저렴한', 'They found an ___ hotel.', '그들은 저렴한 호텔을 찾았다.'],
  ['affordable', '감당할 수 있는', 'The rent is quite ___ .', '그 집세는 꽤 감당할 만하다.'],
  ['overpriced', '값이 비싼', 'The meal felt ___ .', '그 식사는 값이 비싸게 느껴졌다.'],
  ['worthwhile', '가치 있는', 'The trip was ___ .', '그 여행은 가치가 있었다.'],
  ['profitable', '수익성 있는', 'The business became ___ .', '그 사업은 수익성이 있게 되었다.'],
  ['unprofitable', '수익성 없는', 'The store proved ___ .', '그 가게는 수익성이 없는 것으로 드러났다.'],
  ['bankruptcy', '파산', 'The company filed for ___ .', '그 회사는 파산을 신청했다.'],
  ['merchandise', '상품', 'The store sells cheap ___ .', '그 가게는 값싼 상품을 판다.'],
  ['bookkeeping', '부기', 'She handles the ___ for the shop.', '그녀는 그 가게의 부기를 담당한다.'],
  ['spreadsheet', '스프레드시트', 'He updated the ___ daily.', '그는 매일 스프레드시트를 업데이트했다.'],
  ['conference', '회의(컨퍼런스)', 'The ___ starts tomorrow.', '그 컨퍼런스는 내일 시작한다.'],
  ['convention', '대회', 'Thousands attended the ___ .', '수천 명이 그 대회에 참석했다.'],
  ['delegation', '대표단', 'A ___ arrived from abroad.', '해외에서 대표단이 도착했다.'],
  ['ambassador', '대사', 'The ___ met the president.', '그 대사는 대통령을 만났다.'],
  ['parliament', '의회', 'The bill passed ___ .', '그 법안은 의회를 통과했다.'],
  ['dictatorship', '독재 정치', 'The nation escaped ___ .', '그 나라는 독재 정치에서 벗어났다.'],
  ['revolution', '혁명', 'The ___ changed history.', '그 혁명은 역사를 바꿨다.'],
  ['propaganda', '선전', 'The regime spread ___ .', '그 정권은 선전을 퍼뜨렸다.'],
  ['censorship', '검열', 'The film faced strict ___ .', '그 영화는 엄격한 검열을 받았다.'],
  ['surveillance', '감시', 'Cameras provide constant ___ .', '카메라가 지속적인 감시를 제공한다.'],
  ['encryption', '암호화', 'The app uses strong ___ .', '그 앱은 강력한 암호화를 사용한다.'],
  ['programming', '프로그래밍', 'She studies computer ___ .', '그녀는 컴퓨터 프로그래밍을 공부한다.'],
  ['application', '지원서', 'He submitted the job ___ .', '그는 입사 지원서를 제출했다.'],
  ['subscription', '구독', 'She canceled her ___ .', '그녀는 구독을 취소했다.'],
  ['broadcasting', '방송', 'He works in ___ .', '그는 방송업에서 일한다.'],
  ['journalism', '언론학', 'She studied ___ in college.', '그녀는 대학에서 언론학을 공부했다.'],
  ['photography', '사진술', 'He teaches ___ on weekends.', '그는 주말에 사진술을 가르친다.'],
  ['calligraphy', '서예', 'She practices ___ every evening.', '그녀는 매일 저녁 서예를 연습한다.'],
  ['masterpiece', '걸작', 'The painting is a true ___ .', '그 그림은 진정한 걸작이다.'],
  ['exhibition', '전시회', 'They visited the art ___ .', '그들은 그 미술 전시회를 방문했다.'],
  ['collection', '수집품', 'He owns a rare stamp ___ .', '그는 희귀 우표 수집품을 소유하고 있다.'],
  ['handicraft', '수공예품', 'She sells handmade ___ s.', '그녀는 수제 수공예품을 판다.'],
  ['embroidery', '자수', 'The dress has fine ___ .', '그 드레스는 섬세한 자수가 있다.'],
  ['woodcarving', '목각', 'The old ___ hung on the wall.', '그 오래된 목각이 벽에 걸려 있었다.'],
  ['blacksmithing', '대장일', 'He learned ___ from his father.', '그는 아버지에게서 대장일을 배웠다.'],
  ['upholstery', '실내 장식 천', 'The sofa needs new ___ .', '그 소파는 새 실내 장식 천이 필요하다.'],
  ['renovation', '개조', 'The house needs major ___ .', '그 집은 대대적인 개조가 필요하다.'],
  ['demolition', '철거', 'The ___ took only hours.', '그 철거는 단 몇 시간밖에 걸리지 않았다.'],
  ['foundation', '기초', 'The ___ must be solid.', '기초는 튼튼해야 한다.'],
  ['scaffolding', '비계', 'Workers climbed the ___ .', '인부들이 비계를 올랐다.'],
  ['excavation', '굴착', 'The ___ revealed old bones.', '그 굴착으로 오래된 뼈가 드러났다.'],
  ['atmosphere', '대기', 'Earth’s ___ protects us.', '지구의 대기는 우리를 보호한다.'],
  ['visibility', '가시성', 'Fog reduced ___ sharply.', '안개가 가시성을 크게 낮췄다.'],
  ['atmospheric', '대기의', 'They study ___ pressure.', '그들은 대기압을 연구한다.'],
  ['constellation', '별자리', 'He pointed at a bright ___ .', '그는 밝은 별자리를 가리켰다.'],
  ['planetarium', '천체투영관', 'They visited the city ___ .', '그들은 그 도시의 천체투영관을 방문했다.'],
  ['observatory', '천문대', 'Scientists work at the ___ .', '과학자들이 그 천문대에서 일한다.'],
  ['hemisphere', '반구', 'Australia is in the southern ___ .', '호주는 남반구에 있다.'],
  ['continental', '대륙의', 'They study ___ drift.', '그들은 대륙 이동을 연구한다.'],
  ['archipelago', '군도', 'The ___ has hundreds of islands.', '그 군도에는 수백 개의 섬이 있다.'],
  ['topography', '지형', 'The ___ here is rugged.', '이곳의 지형은 험준하다.'],
  ['wilderness', '야생 지역', 'They camped in the ___ .', '그들은 야생 지역에서 캠핑했다.'],
  ['conservation', '보존', 'The group promotes wildlife ___ .', '그 단체는 야생 동물 보존을 촉진한다.'],
  ['biodiversity', '생물 다양성', 'The rainforest has rich ___ .', '그 열대우림은 풍부한 생물 다양성을 가지고 있다.'],
  ['extinction', '멸종', 'The species faces ___ .', '그 종은 멸종 위기에 처해 있다.'],
  ['endangered', '멸종 위기의', 'Pandas are an ___ species.', '판다는 멸종 위기종이다.'],
  ['deforestation', '삼림 벌채', 'Rapid ___ harmed the region.', '급속한 삼림 벌채가 그 지역에 피해를 주었다.'],
  ['reforestation', '재조림', 'The government began ___ efforts.', '정부는 재조림 노력을 시작했다.'],
]

export const WORDS = { easy, normal, hard }

export const LEVELS = [
  { id: 'easy', name: '쉬움', count: 10, desc: '7글자 이하 · 10문제' },
  { id: 'normal', name: '보통', count: 15, desc: '12글자 이하 · 15문제' },
  { id: 'hard', name: '상급', count: 30, desc: '10글자 이상 · 30문제' },
]

/* 난이도별 글자 수 규칙. 사전을 늘릴 때 이 규칙을 어기지 않았는지
   테스트가 여기를 보고 검사한다 — 규칙을 두 군데 적으면 언젠가 어긋난다. */
export const LENGTH_RULE = {
  easy: (w) => w.length <= 7,
  normal: (w) => w.length <= 12,
  hard: (w) => w.length >= 10,
}
export const RULE_TEXT = { easy: '7글자 이하', normal: '12글자 이하', hard: '10글자 이상' }

export const wordsOf = (level) => WORDS[level] || WORDS.easy
export const totalWords = () => easy.length + normal.length + hard.length
