/* ==================================================================
   영어 단어 사전 — 난이도별 200개씩 600개

   한 줄에 [단어, 뜻, 예문] 세 가지를 담는다. 예문의 ___ 자리에
   그 단어가 들어간다 (빈칸 채우기 문제에 쓴다).

   객체 대신 배열로 적은 이유: 600줄이 되면 { word: ..., meaning: ... }
   형식은 읽을 때 눈이 피로하고, 만들어 낸 HTML 파일도 그만큼 커진다.
   줄마다 순서가 같으니 헷갈릴 일도 없다.

   난이도 규칙 (테스트가 이 규칙을 그대로 검사한다)
     easy    7글자 이하
     normal  12글자 이하
     hard    10글자 이상
   ================================================================== */

export const WORD_FIELDS = ['word', 'meaning', 'sentence']

/* ------------------------------------------------------------------
   초급 — 7글자 이하. 일상에서 매일 마주치는 말들.
   ------------------------------------------------------------------ */
const easy = [
  ['apple', '사과', 'She ate a red ___ after lunch.'],
  ['book', '책', 'I borrowed a ___ from the library.'],
  ['water', '물', 'Please drink more ___ every day.'],
  ['happy', '행복한', 'The children look very ___ today.'],
  ['house', '집', 'They bought a small ___ near the park.'],
  ['school', '학교', 'My sister walks to ___ every morning.'],
  ['friend', '친구', 'He is my closest ___ from childhood.'],
  ['family', '가족', 'Our whole ___ gathers every winter.'],
  ['market', '시장', 'We buy fresh fish at the ___ .'],
  ['garden', '정원', 'Roses bloom in her small ___ .'],
  ['animal', '동물', 'The lion is a wild ___ .'],
  ['flower', '꽃', 'He gave her a yellow ___ .'],
  ['summer', '여름', 'We swim in the sea every ___ .'],
  ['winter', '겨울', 'It snows a lot in ___ .'],
  ['spring', '봄', 'Trees turn green in ___ .'],
  ['morning', '아침', 'I drink tea every ___ .'],
  ['night', '밤', 'The stars shine at ___ .'],
  ['kitchen', '부엌', 'Mother is cooking in the ___ .'],
  ['bedroom', '침실', 'My ___ has a large window.'],
  ['window', '창문', 'Please open the ___ for fresh air.'],
  ['table', '탁자', 'Put the plates on the ___ .'],
  ['chair', '의자', 'He sat on a wooden ___ .'],
  ['phone', '전화기', 'My ___ battery died this morning.'],
  ['letter', '편지', 'She wrote a long ___ to her father.'],
  ['music', '음악', 'I listen to ___ while studying.'],
  ['dance', '춤추다', 'They love to ___ at weddings.'],
  ['color', '색깔', 'Blue is my favorite ___ .'],
  ['bread', '빵', 'He baked fresh ___ this morning.'],
  ['cheese', '치즈', 'This pizza has too much ___ .'],
  ['coffee', '커피', 'She drinks black ___ without sugar.'],
  ['sugar', '설탕', 'Add two spoons of ___ .'],
  ['salt', '소금', 'The soup needs more ___ .'],
  ['pepper', '후추', 'Sprinkle some ___ on the eggs.'],
  ['dinner', '저녁 식사', 'We eat ___ together at seven.'],
  ['lunch', '점심', 'I had a quick ___ at my desk.'],
  ['plate', '접시', 'He dropped the glass ___ .'],
  ['spoon', '숟가락', 'Stir the soup with a ___ .'],
  ['knife', '칼', 'Cut the bread with a sharp ___ .'],
  ['glass', '유리잔', 'Pour the juice into a ___ .'],
  ['bottle', '병', 'She carried a ___ of water.'],
  ['basket', '바구니', 'The ___ is full of apples.'],
  ['money', '돈', 'He saved ___ for a new bike.'],
  ['price', '가격', 'The ___ of rice went up.'],
  ['store', '가게', 'That ___ opens at nine.'],
  ['street', '거리', 'Cars filled the narrow ___ .'],
  ['city', '도시', 'Seoul is a busy ___ .'],
  ['town', '마을', 'She grew up in a quiet ___ .'],
  ['river', '강', 'A long ___ runs through the valley.'],
  ['ocean', '바다', 'The ___ looks calm today.'],
  ['beach', '해변', 'We walked along the sandy ___ .'],
  ['forest', '숲', 'Many birds live in this ___ .'],
  ['hill', '언덕', 'They climbed the green ___ .'],
  ['field', '들판', 'Cows graze in the open ___ .'],
  ['island', '섬', 'We took a boat to the ___ .'],
  ['bridge', '다리', 'The old ___ crosses the river.'],
  ['train', '기차', 'The ___ leaves at six sharp.'],
  ['plane', '비행기', 'Our ___ landed on time.'],
  ['ship', '배', 'The ___ sailed at dawn.'],
  ['travel', '여행하다', 'They ___ abroad every summer.'],
  ['ticket', '표', 'I lost my concert ___ .'],
  ['hotel', '호텔', 'We stayed at a small ___ .'],
  ['sleep', '자다', 'Babies ___ most of the day.'],
  ['dream', '꿈', 'She had a strange ___ last night.'],
  ['walk', '걷다', 'Let us ___ to the station.'],
  ['jump', '뛰다', 'The cat can ___ very high.'],
  ['swim', '수영하다', 'He learned to ___ at age five.'],
  ['climb', '오르다', 'They plan to ___ that mountain.'],
  ['throw', '던지다', 'Do not ___ stones at birds.'],
  ['catch', '잡다', 'Try to ___ the ball with both hands.'],
  ['carry', '나르다', 'Can you ___ this heavy box?'],
  ['push', '밀다', 'Please ___ the door gently.'],
  ['pull', '당기다', 'You must ___ the handle hard.'],
  ['open', '열다', 'Could you ___ the window?'],
  ['close', '닫다', 'Remember to ___ the gate.'],
  ['break', '부수다', 'Be careful not to ___ the vase.'],
  ['build', '짓다', 'They will ___ a new library.'],
  ['clean', '청소하다', 'I ___ my room every Saturday.'],
  ['wash', '씻다', 'Please ___ your hands first.'],
  ['cook', '요리하다', 'He likes to ___ Italian food.'],
  ['drink', '마시다', 'Do not ___ cold water too fast.'],
  ['taste', '맛보다', 'Would you like to ___ this soup?'],
  ['smell', '냄새 맡다', 'I can ___ fresh bread.'],
  ['touch', '만지다', 'Do not ___ the wet paint.'],
  ['listen', '귀 기울이다', 'Please ___ to the teacher.'],
  ['speak', '말하다', 'She can ___ three languages.'],
  ['answer', '대답하다', 'He did not ___ my question.'],
  ['write', '쓰다', 'Please ___ your name here.'],
  ['draw', '그리다', 'He can ___ birds very well.'],
  ['learn', '배우다', 'Children ___ quickly at that age.'],
  ['teach', '가르치다', 'She will ___ math next year.'],
  ['study', '공부하다', 'They ___ together every evening.'],
  ['think', '생각하다', 'Let me ___ about it tonight.'],
  ['forget', '잊다', 'Do not ___ your umbrella.'],
  ['hope', '바라다', 'We ___ the weather stays clear.'],
  ['want', '원하다', 'What do you ___ for dinner?'],
  ['love', '사랑하다', 'They ___ their grandchildren dearly.'],
  ['laugh', '웃다', 'His jokes always make us ___ .'],
  ['smile', '미소짓다', 'She began to ___ warmly.'],
  ['shout', '소리치다', 'Do not ___ in the library.'],
  ['help', '돕다', 'Can you ___ me carry this?'],
  ['share', '나누다', 'Please ___ the candy with your sister.'],
  ['bring', '가져오다', 'Do not forget to ___ your notebook.'],
  ['send', '보내다', 'I will ___ the file tonight.'],
  ['sell', '팔다', 'They ___ vegetables at the corner.'],
  ['count', '세다', 'Please ___ the chairs again.'],
  ['number', '숫자', 'Write your phone ___ here.'],
  ['week', '주', 'I will visit you next ___ .'],
  ['month', '달', 'Rent is due every ___ .'],
  ['today', '오늘', 'The test is ___ at noon.'],
  ['hour', '시간', 'We waited for an ___ in the rain.'],
  ['minute', '분', 'Wait one ___ , please.'],
  ['clock', '시계', 'The ___ on the wall stopped.'],
  ['early', '이른', 'She woke up ___ this morning.'],
  ['late', '늦은', 'He was ___ for the meeting.'],
  ['always', '항상', 'He ___ arrives before nine.'],
  ['never', '결코 ~않다', 'She ___ eats meat.'],
  ['often', '자주', 'We ___ meet on Fridays.'],
  ['quick', '빠른', 'He gave a ___ answer.'],
  ['strong', '강한', 'The wind was very ___ .'],
  ['weak', '약한', 'The signal here is too ___ .'],
  ['brave', '용감한', 'The ___ boy saved the puppy.'],
  ['afraid', '두려운', 'She is ___ of tall places.'],
  ['lonely', '외로운', 'He felt ___ in the new city.'],
  ['proud', '자랑스러운', 'Her parents are very ___ .'],
  ['polite', '예의 바른', 'He is always ___ to guests.'],
  ['rude', '무례한', 'That comment was quite ___ .'],
  ['honest', '정직한', 'She gave an ___ opinion.'],
  ['clever', '영리한', 'That was a ___ solution.'],
  ['simple', '단순한', 'The recipe is very ___ .'],
  ['famous', '유명한', 'He is a ___ painter.'],
  ['modern', '현대의', 'They live in a ___ apartment.'],
  ['ancient', '고대의', 'We visited an ___ temple.'],
  ['future', '미래', 'Nobody knows the ___ .'],
  ['past', '과거', 'Do not dwell on the ___ .'],
  ['begin', '시작하다', 'The class will ___ shortly.'],
  ['finish', '끝내다', 'Please ___ your homework first.'],
  ['change', '바꾸다', 'We must ___ the schedule.'],
  ['choose', '고르다', 'You may ___ any seat.'],
  ['decide', '결정하다', 'They will ___ tomorrow.'],
  ['fail', '실패하다', 'Do not be afraid to ___ .'],
  ['leave', '떠나다', 'We ___ for Busan at dawn.'],
  ['arrive', '도착하다', 'They will ___ before noon.'],
  ['return', '돌아오다', 'She will ___ next Monday.'],
  ['follow', '따라가다', 'Please ___ the guide closely.'],
  ['visit', '방문하다', 'We ___ our grandmother weekly.'],
  ['invite', '초대하다', 'They will ___ all the neighbors.'],
  ['thank', '감사하다', 'I want to ___ you sincerely.'],
  ['sorry', '미안한', 'He looked truly ___ .'],
  ['doctor', '의사', 'The ___ examined my throat.'],
  ['nurse', '간호사', 'A kind ___ helped the patient.'],
  ['farmer', '농부', 'The ___ grows rice and beans.'],
  ['artist', '예술가', 'That ___ paints beautiful skies.'],
  ['writer', '작가', 'She is a young ___ .'],
  ['singer', '가수', 'The ___ has a lovely voice.'],
  ['driver', '운전사', 'The bus ___ waved at us.'],
  ['police', '경찰', 'The ___ arrived within minutes.'],
  ['office', '사무실', 'His ___ is on the third floor.'],
  ['company', '회사', 'She works for a small ___ .'],
  ['job', '직업', 'He found a new ___ downtown.'],
  ['work', '일하다', 'They ___ from home on Fridays.'],
  ['meeting', '회의', 'The ___ starts at ten.'],
  ['report', '보고서', 'Please submit your ___ today.'],
  ['plan', '계획', 'We made a careful ___ .'],
  ['idea', '생각', 'That is a wonderful ___ .'],
  ['problem', '문제', 'We solved the ___ together.'],
  ['reason', '이유', 'Give me one good ___ .'],
  ['result', '결과', 'The ___ surprised everyone.'],
  ['story', '이야기', 'Grandmother told a long ___ .'],
  ['news', '소식', 'The ___ spread quickly.'],
  ['picture', '그림', 'Hang the ___ above the sofa.'],
  ['film', '영화', 'That ___ won many awards.'],
  ['game', '게임', 'The ___ lasted three hours.'],
  ['sport', '운동', 'Swimming is a healthy ___ .'],
  ['team', '팀', 'Our ___ won the final match.'],
  ['player', '선수', 'The young ___ scored twice.'],
  ['health', '건강', 'Sleep is vital for good ___ .'],
  ['body', '몸', 'Exercise keeps the ___ strong.'],
  ['heart', '심장', 'His ___ beat quickly.'],
  ['hand', '손', 'She raised her right ___ .'],
  ['voice', '목소리', 'Her ___ was soft and clear.'],
  ['face', '얼굴', 'A smile lit up his ___ .'],
  ['weather', '날씨', 'The ___ turned cold suddenly.'],
  ['cloud', '구름', 'A dark ___ covered the sun.'],
  ['storm', '폭풍', 'The ___ broke many branches.'],
  ['light', '빛', 'The ___ from the lamp was dim.'],
  ['shadow', '그림자', 'His ___ stretched across the road.'],
  ['fire', '불', 'They sat around the warm ___ .'],
  ['stone', '돌', 'He picked up a smooth ___ .'],
  ['metal', '금속', 'The gate is made of ___ .'],
  ['paper', '종이', 'Write it on this ___ .'],
  ['wood', '나무', 'The table is solid ___ .'],
  ['jacket', '재킷', 'Wear a warm ___ outside.'],
  ['shoes', '신발', 'These ___ are too tight.'],
  ['pocket', '주머니', 'The key is in my ___ .'],
  ['mirror', '거울', 'She looked in the ___ .'],
  ['candle', '초', 'A single ___ lit the room.'],
  ['blanket', '담요', 'Pull the ___ over you.'],
  ['pillow', '베개', 'This ___ is very soft.'],
  ['ladder', '사다리', 'He climbed the wooden ___ .'],
  ['hammer', '망치', 'Pass me the heavy ___ .'],
]

/* ------------------------------------------------------------------
   중급 — 12글자 이하. 글이나 대화에서 자주 만나는 말들.
   ------------------------------------------------------------------ */
const normal = [
  ['breakfast', '아침 식사', 'Never skip ___ before a long day.'],
  ['mountain', '산', 'They hiked up the steep ___ .'],
  ['remember', '기억하다', 'I still ___ her kind words.'],
  ['tomorrow', '내일', 'The results arrive ___ morning.'],
  ['beautiful', '아름다운', 'The sunset was truly ___ .'],
  ['dangerous', '위험한', 'That road is ___ at night.'],
  ['difficult', '어려운', 'The exam was quite ___ .'],
  ['important', '중요한', 'Rest is ___ for recovery.'],
  ['necessary', '필요한', 'A visa is ___ for that trip.'],
  ['possible', '가능한', 'It is ___ to finish today.'],
  ['knowledge', '지식', 'She shared her ___ generously.'],
  ['education', '교육', 'Good ___ opens many doors.'],
  ['community', '공동체', 'The ___ raised funds quickly.'],
  ['agreement', '합의', 'They reached an ___ at last.'],
  ['argument', '논쟁', 'The ___ lasted all evening.'],
  ['decision', '결정', 'It was a difficult ___ .'],
  ['direction', '방향', 'We walked in the wrong ___ .'],
  ['election', '선거', 'The ___ was held peacefully.'],
  ['emotion', '감정', 'His voice showed real ___ .'],
  ['attention', '주의', 'Please pay close ___ .'],
  ['solution', '해결책', 'We found a simple ___ .'],
  ['question', '질문', 'That is an excellent ___ .'],
  ['position', '위치', 'Move the lamp to that ___ .'],
  ['condition', '상태', 'The car is in fine ___ .'],
  ['situation', '상황', 'The ___ improved slowly.'],
  ['tradition', '전통', 'This ___ dates back centuries.'],
  ['culture', '문화', 'Food reveals a lot about ___ .'],
  ['history', '역사', 'She teaches Korean ___ .'],
  ['science', '과학', 'Modern ___ advances rapidly.'],
  ['research', '연구', 'His ___ took five years.'],
  ['evidence', '증거', 'The ___ was convincing.'],
  ['theory', '이론', 'That ___ is widely accepted.'],
  ['method', '방법', 'We tried a different ___ .'],
  ['process', '과정', 'The ___ takes several weeks.'],
  ['progress', '진전', 'She made steady ___ .'],
  ['purpose', '목적', 'What is the ___ of this rule?'],
  ['benefit', '이익', 'Exercise has a clear ___ .'],
  ['advantage', '장점', 'Speed is our main ___ .'],
  ['disadvantage', '단점', 'Cost is the main ___ .'],
  ['challenge', '도전', 'The project was a real ___ .'],
  ['opinion', '의견', 'I respect your ___ .'],
  ['suggestion', '제안', 'Thank you for the ___ .'],
  ['statement', '진술', 'He signed the written ___ .'],
  ['announcement', '발표', 'The ___ came this morning.'],
  ['conversation', '대화', 'We had a long ___ .'],
  ['discussion', '토론', 'The ___ grew heated.'],
  ['description', '묘사', 'Her ___ was very vivid.'],
  ['instruction', '지시', 'Follow each ___ carefully.'],
  ['requirement', '요건', 'Experience is a strict ___ .'],
  ['equipment', '장비', 'The ___ arrived yesterday.'],
  ['material', '재료', 'Choose a lighter ___ .'],
  ['product', '제품', 'This ___ sells very well.'],
  ['industry', '산업', 'The film ___ is growing.'],
  ['business', '사업', 'Their ___ expanded abroad.'],
  ['customer', '고객', 'Every ___ deserves respect.'],
  ['service', '서비스', 'The ___ here is excellent.'],
  ['quality', '품질', 'We never compromise on ___ .'],
  ['quantity', '양', 'Order a smaller ___ .'],
  ['increase', '증가하다', 'Prices will ___ next month.'],
  ['decrease', '감소하다', 'Sales began to ___ slowly.'],
  ['develop', '개발하다', 'They ___ new software.'],
  ['improve', '개선하다', 'She wants to ___ her writing.'],
  ['provide', '제공하다', 'We ___ free training.'],
  ['produce', '생산하다', 'This farm can ___ enough rice.'],
  ['consider', '고려하다', 'Please ___ my request.'],
  ['continue', '계속하다', 'They will ___ the search.'],
  ['complete', '완성하다', 'Please ___ the form.'],
  ['prepare', '준비하다', 'We must ___ for the storm.'],
  ['discover', '발견하다', 'Scientists ___ new species yearly.'],
  ['describe', '묘사하다', 'Can you ___ the man?'],
  ['explain', '설명하다', 'Let me ___ the rule again.'],
  ['express', '표현하다', 'She struggled to ___ her feelings.'],
  ['suggest', '제안하다', 'I ___ we leave early.'],
  ['recommend', '추천하다', 'Doctors ___ regular exercise.'],
  ['announce', '발표하다', 'They will ___ the winner soon.'],
  ['achieve', '달성하다', 'He hopes to ___ his goal.'],
  ['succeed', '성공하다', 'She worked hard to ___ .'],
  ['prevent', '예방하다', 'Vaccines ___ many illnesses.'],
  ['protect', '보호하다', 'Trees ___ the soil.'],
  ['support', '지지하다', 'Many people ___ the plan.'],
  ['require', '요구하다', 'These plants ___ little water.'],
  ['include', '포함하다', 'Does the price ___ tax?'],
  ['contain', '담고 있다', 'This box may ___ glass.'],
  ['reduce', '줄이다', 'We must ___ our waste.'],
  ['replace', '대체하다', 'Please ___ the broken part.'],
  ['repair', '수리하다', 'He can ___ old clocks.'],
  ['measure', '측정하다', 'Please ___ the room first.'],
  ['compare', '비교하다', 'Let us ___ the two plans.'],
  ['connect', '연결하다', 'This road will ___ both towns.'],
  ['separate', '분리하다', 'Please ___ the paper and plastic.'],
  ['organize', '조직하다', 'She will ___ the event.'],
  ['manage', '관리하다', 'He can ___ a large team.'],
  ['control', '통제하다', 'Try to ___ your temper.'],
  ['operate', '운영하다', 'They ___ three factories.'],
  ['maintain', '유지하다', 'We must ___ these standards.'],
  ['establish', '설립하다', 'They plan to ___ a school.'],
  ['introduce', '소개하다', 'Let me ___ my colleague.'],
  ['influence', '영향', 'Her ___ on the team was huge.'],
  ['pressure', '압력', 'He works well under ___ .'],
  ['balance', '균형', 'Find a ___ between work and rest.'],
  ['distance', '거리', 'The ___ is about ten kilometers.'],
  ['surface', '표면', 'The ___ felt rough.'],
  ['structure', '구조', 'The ___ needs repair.'],
  ['pattern', '무늬', 'The cloth has a floral ___ .'],
  ['feature', '특징', 'Its best ___ is the screen.'],
  ['element', '요소', 'Trust is a key ___ .'],
  ['factor', '요인', 'Cost was the deciding ___ .'],
  ['effect', '효과', 'The medicine had a quick ___ .'],
  ['impact', '충격', 'The news had a strong ___ .'],
  ['growth', '성장', 'Steady ___ continued all year.'],
  ['success', '성공', 'Her ___ inspired many.'],
  ['failure', '실패', 'The ___ taught us a lot.'],
  ['mistake', '실수', 'Everyone makes a ___ sometimes.'],
  ['accident', '사고', 'The ___ blocked the road.'],
  ['danger', '위험', 'The sign warns of ___ .'],
  ['safety', '안전', 'Wear a helmet for your ___ .'],
  ['risk', '위험 부담', 'Every choice carries some ___ .'],
  ['chance', '기회', 'Give him another ___ .'],
  ['opportunity', '기회', 'This is a rare ___ .'],
  ['ability', '능력', 'She has real ___ in math.'],
  ['skill', '기술', 'Cooking is a useful ___ .'],
  ['talent', '재능', 'He shows great musical ___ .'],
  ['effort', '노력', 'Your ___ finally paid off.'],
  ['practice', '연습', 'Daily ___ makes a difference.'],
  ['experience', '경험', 'Her ___ helped the team.'],
  ['memory', '기억', 'That song brings back a ___ .'],
  ['attitude', '태도', 'His ___ improved quickly.'],
  ['behavior', '행동', 'Her ___ surprised us.'],
  ['character', '성격', 'He has a gentle ___ .'],
  ['personal', '개인의', 'That is a ___ matter.'],
  ['private', '사적인', 'This is a ___ conversation.'],
  ['public', '공공의', 'The park is open to the ___ .'],
  ['general', '일반적인', 'That is the ___ opinion.'],
  ['special', '특별한', 'Today is a ___ occasion.'],
  ['similar', '비슷한', 'The twins have ___ voices.'],
  ['different', '다른', 'Their views are quite ___ .'],
  ['various', '다양한', 'We tried ___ approaches.'],
  ['certain', '확실한', 'I am ___ he will come.'],
  ['obvious', '명백한', 'The answer was ___ .'],
  ['complex', '복잡한', 'The rules are rather ___ .'],
  ['serious', '심각한', 'This is a ___ problem.'],
  ['careful', '조심스러운', 'Be ___ on the wet floor.'],
  ['popular', '인기 있는', 'That song became ___ fast.'],
  ['natural', '자연의', 'This soap uses ___ oils.'],
  ['physical', '신체의', 'Regular ___ activity helps.'],
  ['mental', '정신의', 'Rest supports ___ health.'],
  ['social', '사회의', 'They study ___ change.'],
  ['economic', '경제의', 'The ___ outlook improved.'],
  ['political', '정치의', 'It became a ___ issue.'],
  ['medical', '의료의', 'He needs ___ attention.'],
  ['legal', '법적인', 'She sought ___ advice.'],
  ['financial', '재정의', 'The ___ report is due.'],
  ['available', '이용 가능한', 'No seats are ___ tonight.'],
  ['suitable', '적합한', 'This film is not ___ for children.'],
  ['reliable', '믿을 만한', 'He is a ___ partner.'],
  ['flexible', '유연한', 'Our schedule is ___ .'],
  ['efficient', '효율적인', 'The new system is more ___ .'],
  ['effective', '효과적인', 'That method proved ___ .'],
  ['accurate', '정확한', 'Her measurements were ___ .'],
  ['precise', '정밀한', 'We need a ___ figure.'],
  ['approximate', '대략의', 'Give me an ___ number.'],
  ['average', '평균의', 'His score was above ___ .'],
  ['maximum', '최대의', 'The ___ speed is eighty.'],
  ['minimum', '최소의', 'There is a ___ order.'],
  ['recent', '최근의', 'A ___ study confirmed it.'],
  ['current', '현재의', 'The ___ rate is low.'],
  ['previous', '이전의', 'Check the ___ chapter.'],
  ['following', '다음의', 'Read the ___ passage.'],
  ['further', '더 이상의', 'No ___ action is needed.'],
  ['whole', '전체의', 'She read the ___ book.'],
  ['entire', '전체의', 'The ___ village celebrated.'],
  ['several', '여럿의', 'He asked ___ questions.'],
  ['multiple', '다수의', 'There were ___ reasons.'],
  ['single', '단 하나의', 'Not a ___ light was on.'],
  ['double', '두 배의', 'Order a ___ portion.'],
  ['exact', '정확한', 'Tell me the ___ time.'],
  ['final', '마지막의', 'This is the ___ round.'],
  ['initial', '처음의', 'Our ___ plan failed.'],
  ['original', '원래의', 'The ___ copy is missing.'],
  ['additional', '추가의', 'We need ___ chairs.'],
  ['sufficient', '충분한', 'Bring ___ water.'],
  ['adequate', '적당한', 'The lighting is ___ .'],
  ['constant', '끊임없는', 'There was ___ noise outside.'],
  ['frequent', '잦은', 'He is a ___ visitor.'],
  ['occasional', '가끔의', 'We take ___ breaks.'],
  ['temporary', '일시적인', 'This is a ___ solution.'],
  ['permanent', '영구적인', 'She found a ___ job.'],
  ['ordinary', '평범한', 'It was an ___ Tuesday.'],
  ['unusual', '흔치 않은', 'That is an ___ color.'],
  ['familiar', '익숙한', 'The tune sounded ___ .'],
  ['foreign', '외국의', 'She studies a ___ language.'],
  ['distant', '먼', 'They come from a ___ island.'],
  ['nearby', '가까운', 'Is there a ___ pharmacy?'],
  ['central', '중심의', 'The ___ office moved.'],
  ['northern', '북쪽의', 'The ___ region is colder.'],
  ['southern', '남쪽의', 'The ___ coast is warmer.'],
  ['eastern', '동쪽의', 'The ___ sky brightened.'],
  ['western', '서쪽의', 'They drove to the ___ border.'],
  ['vegetable', '채소', 'Eat one green ___ each day.'],
  ['furniture', '가구', 'They bought new ___ for the flat.'],
]

/* ------------------------------------------------------------------
   상급 — 10글자 이상. 시험이나 글에서 만나는 긴 말들.
   ------------------------------------------------------------------ */
const hard = [
  ['responsibility', '책임', 'Taking ___ is part of growing up.'],
  ['extraordinary', '비범한', 'She showed ___ courage.'],
  ['international', '국제의', 'They signed an ___ treaty.'],
  ['understanding', '이해', 'We reached a mutual ___ .'],
  ['consideration', '고려', 'Please give it careful ___ .'],
  ['recommendation', '추천', 'His ___ helped me greatly.'],
  ['characteristic', '특징', 'Patience is her main ___ .'],
  ['representative', '대표', 'A union ___ spoke first.'],
  ['administration', '행정', 'The new ___ took office.'],
  ['communication', '의사소통', 'Clear ___ prevents mistakes.'],
  ['determination', '결단력', 'Her ___ impressed everyone.'],
  ['investigation', '조사', 'The ___ lasted six months.'],
  ['organization', '조직', 'The ___ helps refugees.'],
  ['performance', '성과', 'His ___ improved steadily.'],
  ['relationship', '관계', 'Their ___ grew stronger.'],
  ['significant', '중대한', 'That was a ___ discovery.'],
  ['sustainable', '지속 가능한', 'We need ___ energy sources.'],
  ['sophisticated', '정교한', 'The device is highly ___ .'],
  ['comprehensive', '포괄적인', 'They wrote a ___ report.'],
  ['controversial', '논란이 많은', 'The decision was ___ .'],
  ['demonstration', '시연', 'The ___ drew a large crowd.'],
  ['environmental', '환경의', 'They study ___ damage.'],
  ['fundamental', '근본적인', 'This is a ___ principle.'],
  ['independence', '독립', 'The colony gained ___ .'],
  ['intelligence', '지능', 'Artificial ___ is advancing.'],
  ['nevertheless', '그럼에도', 'It rained; ___ , we went.'],
  ['overwhelming', '압도적인', 'The response was ___ .'],
  ['participation', '참여', 'Student ___ was high.'],
  ['philosophical', '철학적인', 'He raised a ___ question.'],
  ['preliminary', '예비의', 'These are ___ results.'],
  ['psychological', '심리적인', 'The strain was ___ .'],
  ['qualification', '자격', 'She has every ___ needed.'],
  ['recognition', '인정', 'His work finally gained ___ .'],
  ['remarkable', '놀라운', 'It was a ___ recovery.'],
  ['revolutionary', '혁명적인', 'The idea was ___ .'],
  ['spectacular', '장관인', 'The view was ___ .'],
  ['technological', '기술의', '___ progress never stops.'],
  ['transformation', '변화', 'The ___ took a decade.'],
  ['unfortunately', '불행히도', '___ , the flight was canceled.'],
  ['accommodation', '숙박 시설', 'The ___ was clean and quiet.'],
  ['accomplishment', '업적', 'That was a real ___ .'],
  ['advertisement', '광고', 'The ___ ran for a month.'],
  ['appreciation', '감사', 'She expressed deep ___ .'],
  ['architecture', '건축', 'Roman ___ still stands.'],
  ['circumstance', '상황', 'Under no ___ should you enter.'],
  ['collaboration', '협력', 'The ___ produced great work.'],
  ['competition', '경쟁', 'The ___ was fierce.'],
  ['concentration', '집중', 'The task requires ___ .'],
  ['consequence', '결과', 'He faced the ___ calmly.'],
  ['constitution', '헌법', 'The ___ protects free speech.'],
  ['contribution', '기여', 'Her ___ was invaluable.'],
  ['cooperation', '협조', 'Thank you for your ___ .'],
  ['corporation', '기업', 'A large ___ bought the land.'],
  ['correspondence', '서신', 'Their ___ lasted years.'],
  ['disappointed', '실망한', 'She looked deeply ___ .'],
  ['discrimination', '차별', 'The law bans ___ .'],
  ['distribution', '분배', 'The ___ was uneven.'],
  ['documentation', '문서', 'Bring all the ___ .'],
  ['effectiveness', '효과', 'They measured its ___ .'],
  ['encouragement', '격려', 'Her ___ kept me going.'],
  ['entertainment', '오락', 'The ___ lasted all evening.'],
  ['enthusiasm', '열정', 'He spoke with ___ .'],
  ['environment', '환경', 'We must protect the ___ .'],
  ['establishment', '설립', 'The ___ of the fund took years.'],
  ['examination', '시험', 'The ___ begins at nine.'],
  ['expectation', '기대', 'The result exceeded every ___ .'],
  ['explanation', '설명', 'His ___ made sense.'],
  ['exploration', '탐험', 'Space ___ continues.'],
  ['imagination', '상상력', 'Children have vivid ___ .'],
  ['implementation', '시행', 'The ___ starts in May.'],
  ['improvement', '개선', 'There is room for ___ .'],
  ['independent', '독립적인', 'She became financially ___ .'],
  ['individual', '개인', 'Each ___ has a role.'],
  ['industrial', '산업의', 'The ___ zone expanded.'],
  ['infrastructure', '기반 시설', 'The ___ needs investment.'],
  ['initiative', '주도권', 'He took the ___ himself.'],
  ['innovation', '혁신', '___ drives their success.'],
  ['inspiration', '영감', 'Nature was her ___ .'],
  ['institution', '기관', 'The ___ was founded in 1890.'],
  ['interaction', '상호작용', 'Social ___ matters to children.'],
  ['interpretation', '해석', 'Her ___ differed from mine.'],
  ['introduction', '소개', 'The ___ was rather long.'],
  ['investment', '투자', 'The ___ paid off well.'],
  ['legislation', '법률', 'New ___ passed last month.'],
  ['maintenance', '유지 보수', 'Regular ___ prevents damage.'],
  ['manufacture', '제조하다', 'They ___ medical devices.'],
  ['negotiation', '협상', 'The ___ lasted all night.'],
  ['observation', '관찰', 'That is a sharp ___ .'],
  ['occupation', '직업', 'State your ___ here.'],
  ['perspective', '관점', 'Try another ___ .'],
  ['possibility', '가능성', 'There is a slight ___ .'],
  ['preparation', '준비', 'The ___ took weeks.'],
  ['presentation', '발표', 'Her ___ was clear.'],
  ['production', '생산', 'Steel ___ increased.'],
  ['profession', '직업', 'Teaching is a noble ___ .'],
  ['protection', '보호', 'Wear gloves for ___ .'],
  ['publication', '출판', 'The ___ date moved.'],
  ['reflection', '반영', 'Sales are a ___ of quality.'],
  ['regulation', '규정', 'Every ___ must be followed.'],
  ['reputation', '평판', 'The shop has a good ___ .'],
  ['resistance', '저항', 'They met strong ___ .'],
  ['resolution', '결의', 'The council passed a ___ .'],
  ['satisfaction', '만족', 'She smiled with ___ .'],
  ['significance', '중요성', 'Few grasped its ___ .'],
  ['specialist', '전문가', 'Ask a ___ about it.'],
  ['statistics', '통계', 'The ___ tell a clear story.'],
  ['supervision', '감독', 'Work under close ___ .'],
  ['technology', '기술', 'Modern ___ changed everything.'],
  ['temperature', '온도', 'The ___ dropped sharply.'],
  ['university', '대학교', 'He entered ___ last year.'],
  ['acknowledge', '인정하다', 'Please ___ receipt of this.'],
  ['accumulate', '축적하다', 'Dust tends to ___ here.'],
  ['anticipate', '예상하다', 'We ___ heavy traffic.'],
  ['appreciate', '감사하다', 'I truly ___ your help.'],
  ['approximately', '대략', 'It costs ___ fifty dollars.'],
  ['assumption', '가정', 'That ___ proved wrong.'],
  ['collaborate', '협력하다', 'The two teams will ___ .'],
  ['commitment', '헌신', 'Her ___ never wavered.'],
  ['compensate', '보상하다', 'They will ___ the loss.'],
  ['competitive', '경쟁적인', 'The market is very ___ .'],
  ['comprehend', '이해하다', 'It is hard to ___ the scale.'],
  ['concentrate', '집중하다', 'Please ___ on the task.'],
  ['confidence', '자신감', 'She spoke with ___ .'],
  ['confirmation', '확인', 'We await written ___ .'],
  ['consequently', '결과적으로', 'It rained; ___ , we stayed.'],
  ['considerable', '상당한', 'It required ___ effort.'],
  ['consistent', '일관된', 'His results are ___ .'],
  ['constructive', '건설적인', 'She gave ___ feedback.'],
  ['contemporary', '현대의', 'This is ___ music.'],
  ['controversy', '논란', 'The film caused ___ .'],
  ['conventional', '관습적인', 'They chose a ___ approach.'],
  ['convincing', '설득력 있는', 'His argument was ___ .'],
  ['coordination', '조정', 'The task needs ___ .'],
  ['definitely', '분명히', 'I will ___ attend.'],
  ['dependence', '의존', 'Reduce your ___ on cars.'],
  ['desperately', '필사적으로', 'He searched ___ .'],
  ['distinguish', '구별하다', 'Can you ___ the two sounds?'],
  ['distinctive', '독특한', 'It has a ___ flavor.'],
  ['dramatically', '극적으로', 'Costs rose ___ .'],
  ['accessibility', '접근성', 'They improved website ___ .'],
  ['accountability', '책임', 'Voters demanded ___ .'],
  ['essentially', '본질적으로', 'They are ___ the same.'],
  ['achievement', '성취', 'Winning was a huge ___ .'],
  ['eventually', '결국', 'She ___ agreed.'],
  ['exaggerate', '과장하다', 'Do not ___ the danger.'],
  ['exceptional', '뛰어난', 'The service was ___ .'],
  ['expenditure', '지출', 'Cut unnecessary ___ .'],
  ['experiment', '실험', 'The ___ succeeded.'],
  ['fascinating', '매혹적인', 'The lecture was ___ .'],
  ['frequently', '자주', 'He travels ___ .'],
  ['generation', '세대', 'Each ___ faces new problems.'],
  ['advancement', '발전', 'Medical ___ saves lives.'],
  ['illustrate', '설명하다', 'Let me ___ with an example.'],
  ['immediately', '즉시', 'Call me ___ .'],
  ['impressive', '인상적인', 'The result was ___ .'],
  ['incredible', '믿기 힘든', 'The story sounds ___ .'],
  ['inevitable', '피할 수 없는', 'Change was ___ .'],
  ['influential', '영향력 있는', 'She is an ___ critic.'],
  ['ingredient', '재료', 'Salt is a key ___ .'],
  ['inhabitant', '주민', 'Every ___ was evacuated.'],
  ['insufficient', '불충분한', 'The funds were ___ .'],
  ['intellectual', '지적인', 'It was an ___ debate.'],
  ['investigate', '조사하다', 'Police will ___ the case.'],
  ['justification', '정당화', 'There is no ___ for it.'],
  ['legitimate', '정당한', 'She raised a ___ concern.'],
  ['magnificent', '웅장한', 'The hall was ___ .'],
  ['manipulate', '조종하다', 'Do not ___ the data.'],
  ['measurement', '측정', 'Take an exact ___ .'],
  ['mysterious', '신비한', 'A ___ light appeared.'],
  ['alternative', '대안', 'Is there a cheaper ___ ?'],
  ['nutritious', '영양가 있는', 'Beans are highly ___ .'],
  ['obligation', '의무', 'You have no ___ to answer.'],
  ['occasionally', '가끔', 'We meet ___ .'],
  ['originally', '원래', 'It was ___ a barn.'],
  ['outstanding', '뛰어난', 'Her essay was ___ .'],
  ['particularly', '특히', 'It is ___ cold today.'],
  ['persuasive', '설득력 있는', 'He gave a ___ speech.'],
  ['phenomenon', '현상', 'This ___ puzzles scientists.'],
  ['photograph', '사진', 'She framed the old ___ .'],
  ['population', '인구', 'The ___ doubled in ten years.'],
  ['practically', '사실상', 'The work is ___ done.'],
  ['prediction', '예측', 'His ___ proved accurate.'],
  ['prescription', '처방전', 'Bring your ___ to the counter.'],
  ['presumably', '아마도', 'He is ___ still asleep.'],
  ['previously', '이전에', 'We ___ met in Seoul.'],
  ['prohibited', '금지된', 'Smoking is strictly ___ .'],
  ['proportion', '비율', 'A large ___ agreed.'],
  ['reasonable', '합리적인', 'The price seems ___ .'],
  ['reluctantly', '마지못해', 'She ___ accepted.'],
  ['representation', '대표', 'They demanded fair ___ .'],
  ['respectively', '각각', 'They finished first and third, ___ .'],
  ['restriction', '제한', 'The ___ was lifted.'],
  ['simultaneously', '동시에', 'Both alarms rang ___ .'],
  ['specifically', '구체적으로', 'He asked ___ about cost.'],
  ['substantial', '상당한', 'They made a ___ profit.'],
  ['sufficiently', '충분히', 'The soup is ___ warm.'],
  ['surprisingly', '놀랍게도', '___ , nobody complained.'],
  ['unexpectedly', '예기치 않게', 'He arrived ___ early.'],
  ['consciousness', '의식', 'He regained ___ after an hour.'],
  ['contradiction', '모순', 'Her story contained a ___ .'],
]

export const WORDS = { easy, normal, hard }

export const LEVELS = [
  { id: 'easy', name: '쉬움', count: 10, desc: '7글자 이하 · 10문제' },
  { id: 'normal', name: '보통', count: 15, desc: '12글자 이하 · 15문제' },
  { id: 'hard', name: '상급', count: 30, desc: '10글자 이상 · 30문제' },
]

/* 난이도별 글자 수 규칙. 사전을 늘릴 때 이 규칙을 어기지 않았는지
   테스트가 여기를 보고 검사한다 — 규칙을 두 군데 적으면 언젠가 어긋난다. */
export const LENGTH_RULE = {
  easy: (w) => w.length <= 7,
  normal: (w) => w.length <= 12,
  hard: (w) => w.length >= 10,
}
export const RULE_TEXT = { easy: '7글자 이하', normal: '12글자 이하', hard: '10글자 이상' }

export const wordsOf = (level) => WORDS[level] || WORDS.easy
export const totalWords = () => easy.length + normal.length + hard.length
